import {
  FactoryExecutionTask,
  DigitalWorksheetRecord,
  ControlledTechnicalDocument,
  DailyFactoryActivityReport,
  MediaEvidenceRecord,
  FactoryQualityInspectionRecord,
  FactoryDispatchAndSiteRecord,
  FactoryApprovalMatrixRule,
  GeneratedFactoryDocument,
  OfflineSyncQueueItem
} from '../types/factoryPortal';

export const SEED_TASKS: FactoryExecutionTask[] = [
  {
    id: 'ftask-101',
    taskCode: 'WO-2026-101',
    orderType: 'Work Order',
    workPackageId: 'fwp-01',
    workPackageCode: 'FWP-2026-001',
    projectId: 'Sirius Mall Storefront',
    projectName: 'Sirius Mall High-Rise Curtain Wall',
    factoryId: 'fac-inv-01',
    factoryName: 'Innovista Central Facade & Curtain Wall Plant (Biyagama)',
    productionAreaId: 'pa-01',
    productionAreaName: '5-Axis CNC & Double Mitre Cutting Bay',
    title: '5-Axis CNC Milling & Double-Mitre Cutting of Mullion/Transom Profiles (Batch B4)',
    operationStep: 'Step 10: CNC 5-Axis Profile Milling & Mitre Cutting',
    capabilityRequired: 'CNC Machining & Milling',
    drawingNumber: 'DRW-SM-CW-101',
    drawingRevision: 'Rev C',
    latestApprovedRevision: 'Rev C',
    workerConfirmedLatestRevision: true,
    confirmedByWorkerName: 'Roshan Mendis',
    confirmedAt: '2026-09-20T07:30:00Z',
    methodStatementRef: 'MOS-FAB-CW-01',
    checklistTemplateCode: 'CHK-CNC-ALU-01',
    supervisorName: 'Roshan Mendis',
    assignedWorkerIds: ['emp-001', 'emp-003'],
    assignedWorkerNames: ['Roshan Mendis', 'Pradeep Kumara'],
    assignedMachineIds: ['EQ-CNC-01', 'EQ-SAW-02'],
    assignedMachineNames: ['Elumatec SBZ 151 5-Axis CNC Center', 'Elumatec DG 244 Double Mitre Saw'],
    unit: 'Frame Sets',
    plannedQuantity: 60,
    completedQuantity: 60,
    rejectedQuantity: 0,
    reworkQuantity: 1,
    remainingQuantity: 0,
    plannedHours: 48,
    actualHours: 45,
    cycleTimeMinutesPerUnit: 45,
    priority: 'Critical',
    startDate: '2026-09-18',
    targetDate: '2026-09-24',
    actualCompletionDate: '2026-09-24',
    stageStatus: 'Approved',
    predecessorTaskIds: [],
    requiresMaterialIssueComplete: true,
    requiresDrawingConfirmation: true,
    requiresQualityInspectionPass: true,
    requiresHsePermitActive: false,
    linkedInspectionId: 'finsp-01',
    cuttingList: [
      { id: 'cl-1', barOrSheetRef: 'BAR-6063-6000', profileOrMaterialCode: 'PRF-CW-M150', description: 'Main Vertical Mullion 150x65mm', cutLengthMm: 3850, angleLeftDeg: 90, angleRightDeg: 90, quantityRequired: 120, quantityCut: 120, offcutLengthMm: 2150, scrapMm: 45, status: 'Verified' },
      { id: 'cl-2', barOrSheetRef: 'BAR-6063-6000', profileOrMaterialCode: 'PRF-CW-T120', description: 'Horizontal Transom 120x60mm', cutLengthMm: 1498, angleLeftDeg: 90, angleRightDeg: 90, quantityRequired: 180, quantityCut: 180, offcutLengthMm: 6, scrapMm: 6, status: 'Verified' }
    ],
    materials: [
      { id: 'tm-1', inventoryItemId: 'inv-001', itemCode: 'MAT-ALU-150', materialName: '6063-T6 Mullion Extrusion 150x65mm (6m Bars)', unit: 'Bars', requiredQty: 120, issuedQty: 122, consumedQty: 120, returnedQty: 1, wastageQty: 1, scrapQty: 1, shortageQty: 0, batchHeatLotNo: 'LOT-AL-8841', status: 'Fully Issued' }
    ],
    isBottleneck: false,
    delayHours: 0,
    externalPartnerAccepted: true,
    audit: {
      createdBy: 'Eng. Nuwan Senanayake',
      createdByRole: 'Chief Engineer',
      createdAt: '2026-09-17T10:00:00Z',
      updatedBy: 'Marcus Silva',
      updatedByRole: 'QA Lead',
      updatedAt: '2026-09-24T16:00:00Z',
      revision: 2,
      status: 'Approved',
      approvalHistory: [
        { stage: 'Dimensional QC Verification', actorName: 'Marcus Silva', actorRole: 'QA Lead', decision: 'Approved', timestamp: '2026-09-24T16:00:00Z', remarks: 'All 60 frame sets within ±0.5mm CNC tolerance.' }
      ]
    }
  },
  {
    id: 'ftask-102',
    taskCode: 'JC-2026-102',
    orderType: 'Job Card',
    workPackageId: 'fwp-01',
    workPackageCode: 'FWP-2026-001',
    projectId: 'Sirius Mall Storefront',
    projectName: 'Sirius Mall High-Rise Curtain Wall',
    factoryId: 'fac-inv-01',
    factoryName: 'Innovista Central Facade & Curtain Wall Plant (Biyagama)',
    productionAreaId: 'pa-03',
    productionAreaName: 'Climate-Controlled Structural Glazing Room',
    title: 'Unitized Frame Crimping & Two-Part Structural Silicone DGU Bonding (Batch B4)',
    operationStep: 'Step 20: Frame Assembly & Structural Silicone Glazing',
    capabilityRequired: 'Structural Glazing & Silicone',
    drawingNumber: 'DRW-SM-CW-101',
    drawingRevision: 'Rev C',
    latestApprovedRevision: 'Rev C',
    workerConfirmedLatestRevision: true,
    confirmedByWorkerName: 'Kasun Perera',
    confirmedAt: '2026-09-24T08:00:00Z',
    methodStatementRef: 'MOS-FAB-CW-01',
    checklistTemplateCode: 'CHK-GLZ-SIL-02',
    supervisorName: 'Kasun Perera',
    assignedWorkerIds: ['emp-003', 'emp-004'],
    assignedWorkerNames: ['Pradeep Kumara', 'Kasun Perera'],
    assignedMachineIds: ['EQ-CRN-01'],
    assignedMachineNames: ['Graco 2-Part Silicone Metering Pump & Vacuum Manipulator'],
    unit: 'Panels',
    plannedQuantity: 60,
    completedQuantity: 42,
    rejectedQuantity: 1,
    reworkQuantity: 2,
    remainingQuantity: 18,
    plannedHours: 72,
    actualHours: 51,
    cycleTimeMinutesPerUnit: 68,
    priority: 'Critical',
    startDate: '2026-09-24',
    targetDate: '2026-09-29',
    stageStatus: 'In Progress',
    predecessorTaskIds: ['ftask-101'],
    requiresMaterialIssueComplete: true,
    requiresDrawingConfirmation: true,
    requiresQualityInspectionPass: true,
    requiresHsePermitActive: true,
    linkedHsePermitNo: 'WPT-2026-081',
    cuttingList: [],
    materials: [
      { id: 'tm-2', inventoryItemId: 'inv-002', itemCode: 'MAT-GLS-DGU28', materialName: '28mm Low-E Tempered DGU Vision Glass Panels', unit: 'Panels', requiredQty: 60, issuedQty: 60, consumedQty: 42, returnedQty: 0, wastageQty: 0, scrapQty: 0, shortageQty: 0, batchHeatLotNo: 'LOT-GL-3092', status: 'Fully Issued' },
      { id: 'tm-3', inventoryItemId: 'inv-003', itemCode: 'MAT-SIL-DC993', materialName: 'Dow Corning 993 2-Part Structural Glazing Silicone', unit: 'Drums', requiredQty: 6, issuedQty: 6, consumedQty: 4, returnedQty: 0, wastageQty: 0.2, scrapQty: 0, shortageQty: 0, batchHeatLotNo: 'LOT-DC-9921', status: 'Fully Issued' }
    ],
    isBottleneck: false,
    delayHours: 0,
    externalPartnerAccepted: true,
    audit: {
      createdBy: 'Eng. Nuwan Senanayake',
      createdByRole: 'Chief Engineer',
      createdAt: '2026-09-23T14:00:00Z',
      updatedBy: 'Kasun Perera',
      updatedByRole: 'Glazing Supervisor',
      updatedAt: '2026-09-26T06:30:00Z',
      revision: 2,
      status: 'In Progress',
      approvalHistory: []
    }
  },
  {
    id: 'ftask-103',
    taskCode: 'FO-2026-205',
    orderType: 'Fabrication Order',
    workPackageId: 'fwp-02',
    workPackageCode: 'FWP-2026-002',
    projectId: 'Apex Tower Structural Glazing',
    projectName: 'Apex Tower Structural Glazing',
    factoryId: 'fac-inv-02',
    factoryName: 'Innovista Heavy Structural Steel & Welding Workshop (Peliyagoda)',
    productionAreaId: 'pa-202',
    productionAreaName: 'Heavy Truss & Bracket Welding Hall',
    title: 'Full-Penetration MIG/TIG Welding of Atrium Spider Steel Trusses (TR-01 to TR-16)',
    operationStep: 'Step 30: Structural Fit-Up, Full-Penetration Welding & UT NDT',
    capabilityRequired: 'Structural Welding (AWS/ISO)',
    drawingNumber: 'DRW-APX-STL-04',
    drawingRevision: 'Rev D',
    latestApprovedRevision: 'Rev D',
    workerConfirmedLatestRevision: true,
    confirmedByWorkerName: 'Lalith Rodrigo',
    confirmedAt: '2026-09-19T08:00:00Z',
    methodStatementRef: 'MOS-STL-WLD-04',
    checklistTemplateCode: 'CHK-WLD-AWSD11',
    supervisorName: 'Lalith Rodrigo',
    assignedWorkerIds: ['emp-002', 'emp-005'],
    assignedWorkerNames: ['Lalith Rodrigo', 'Saman Kumara'],
    assignedMachineIds: ['EQ-WLD-01'],
    assignedMachineNames: ['Fronius TransSteel 5000 Pulse Welder Bank'],
    unit: 'Trusses',
    plannedQuantity: 16,
    completedQuantity: 14,
    rejectedQuantity: 1,
    reworkQuantity: 1,
    remainingQuantity: 2,
    plannedHours: 120,
    actualHours: 112,
    cycleTimeMinutesPerUnit: 420,
    priority: 'High',
    startDate: '2026-09-15',
    targetDate: '2026-09-27',
    stageStatus: 'Submitted for Inspection',
    predecessorTaskIds: [],
    requiresMaterialIssueComplete: true,
    requiresDrawingConfirmation: true,
    requiresQualityInspectionPass: true,
    requiresHsePermitActive: true,
    linkedHsePermitNo: 'WPT-2026-079',
    linkedInspectionId: 'finsp-02',
    cuttingList: [
      { id: 'cl-3', barOrSheetRef: 'PLT-S355-20MM', profileOrMaterialCode: 'STL-GUSSET-20', description: '20mm S355JR Laser Cut Spider Node Gusset Plate', cutLengthMm: 650, cutWidthMm: 480, angleLeftDeg: 90, angleRightDeg: 45, quantityRequired: 64, quantityCut: 64, offcutLengthMm: 120, scrapMm: 18, status: 'Verified' }
    ],
    materials: [
      { id: 'tm-4', inventoryItemId: 'inv-004', itemCode: 'MAT-STL-CHS219', materialName: 'S355J2H Circular Hollow Section 219.1 x 12.5mm', unit: 'Meters', requiredQty: 192, issuedQty: 192, consumedQty: 174, returnedQty: 0, wastageQty: 4, scrapQty: 2, shortageQty: 0, batchHeatLotNo: 'HEAT-ES-99201', status: 'Fully Issued' }
    ],
    isBottleneck: true,
    delayHours: 6,
    delayReason: 'Ultrasonic NDT root-pass porosity rework on Truss TR-09 node joint',
    externalPartnerAccepted: true,
    audit: {
      createdBy: 'Eng. Janaka Perera',
      createdByRole: 'Workshop Manager',
      createdAt: '2026-09-14T09:00:00Z',
      updatedBy: 'Lalith Rodrigo',
      updatedByRole: 'Welding Supervisor',
      updatedAt: '2026-09-26T05:45:00Z',
      revision: 3,
      status: 'Submitted for Inspection',
      approvalHistory: [
        { stage: 'Submitted for UT NDT Inspection', actorName: 'Lalith Rodrigo', actorRole: 'Welding Supervisor', decision: 'Submitted', timestamp: '2026-09-26T05:45:00Z', remarks: '14 trusses ready for QA UT scan.' }
      ]
    }
  },
  {
    id: 'ftask-104',
    taskCode: 'PO-2026-308',
    orderType: 'Production Order',
    workPackageId: 'fwp-03',
    workPackageCode: 'FWP-2026-003',
    projectId: 'Emerald Pavilion Louvre & Canopy',
    projectName: 'Emerald Pavilion Louvre & Canopy',
    factoryId: 'fac-ext-03',
    factoryName: 'Alumex & Qualicoat Architectural Coating Partner Plant (Sapugaskanda)',
    productionAreaId: 'pa-302',
    productionAreaName: '3D CNC ACP Routing & Cassette Folding Cell',
    title: 'PVDF Champagne Gold Coating & CNC 4mm A2 Fire-Rated ACP Cassette Folding',
    operationStep: 'Step 15: PVDF Coating, CNC V-Groove Routing & Return Flange Riveting',
    capabilityRequired: 'ACP Routing & Folding',
    drawingNumber: 'DRW-EMR-ACP-11',
    drawingRevision: 'Rev B',
    latestApprovedRevision: 'Rev B',
    workerConfirmedLatestRevision: true,
    confirmedByWorkerName: 'Chathura Alwis',
    confirmedAt: '2026-09-18T08:15:00Z',
    methodStatementRef: 'MOS-COAT-PVDF-02',
    checklistTemplateCode: 'CHK-ACP-CAS-01',
    supervisorName: 'Chathura Alwis',
    assignedWorkerIds: ['emp-003'],
    assignedWorkerNames: ['Chathura Alwis'],
    assignedMachineIds: ['EQ-CNC-02'],
    assignedMachineNames: ['Tekcel VSR Vertical ACP CNC Router'],
    unit: 'Cassettes',
    plannedQuantity: 160,
    completedQuantity: 152,
    rejectedQuantity: 2,
    reworkQuantity: 3,
    remainingQuantity: 8,
    plannedHours: 80,
    actualHours: 74,
    cycleTimeMinutesPerUnit: 28,
    priority: 'High',
    startDate: '2026-09-16',
    targetDate: '2026-09-28',
    stageStatus: 'Ready',
    predecessorTaskIds: [],
    requiresMaterialIssueComplete: true,
    requiresDrawingConfirmation: true,
    requiresQualityInspectionPass: true,
    requiresHsePermitActive: false,
    linkedInspectionId: 'finsp-03',
    cuttingList: [],
    materials: [
      { id: 'tm-5', inventoryItemId: 'inv-005', itemCode: 'MAT-ACP-A2-4MM', materialName: 'Alucobond A2 Non-Combustible 4mm Sheet (1500x4000mm)', unit: 'Sheets', requiredQty: 165, issuedQty: 165, consumedQty: 154, returnedQty: 0, wastageQty: 3, scrapQty: 2, shortageQty: 0, batchHeatLotNo: 'LOT-ALU-5521', status: 'Fully Issued' }
    ],
    isBottleneck: false,
    delayHours: 0,
    externalPartnerAccepted: true,
    externalPartnerAcceptedAt: '2026-09-15T11:20:00Z',
    audit: {
      createdBy: 'Marcus Sterling',
      createdByRole: 'Project Manager',
      createdAt: '2026-09-15T09:00:00Z',
      updatedBy: 'Sanjeewa Dias',
      updatedByRole: 'Partner Operations Director',
      updatedAt: '2026-09-25T16:10:00Z',
      revision: 2,
      status: 'Ready',
      approvalHistory: []
    }
  }
];

export const SEED_WORKSHEETS: DigitalWorksheetRecord[] = [
  {
    id: 'dws-01',
    worksheetNo: 'DWS-2026-0089',
    activityType: 'Unitized Curtain Wall Assembly',
    projectId: 'Sirius Mall Storefront',
    projectName: 'Sirius Mall High-Rise Curtain Wall',
    factoryId: 'fac-inv-01',
    factoryName: 'Innovista Central Facade & Curtain Wall Plant (Biyagama)',
    workPackageId: 'fwp-01',
    taskId: 'ftask-102',
    taskCode: 'JC-2026-102',
    drawingNumber: 'DRW-SM-CW-101',
    drawingRevision: 'Rev C',
    recordedDate: '2026-09-25',
    shift: 'Morning Shift',
    recordedByWorkerName: 'Kasun Perera',
    verifiedBySupervisorName: 'Eng. Nuwan Senanayake',
    machineId: 'EQ-CNC-01',
    machineName: 'Graco 2-Part Silicone Pump & Crimping Station',
    machineMeterReadingStart: 1420.5,
    machineMeterReadingEnd: 1428.0,
    labourHoursLogged: 32,
    plannedQtyForShift: 12,
    producedQty: 12,
    acceptedQty: 11,
    rejectedQty: 0,
    reworkQty: 1,
    materialConsumedSummary: '12 Sets 6063-T6 Frame Profiles, 12 DGU 28mm Panels, 18 Liters Dow Corning 993',
    wastageRecordedQty: 0.4,
    wastageUnit: 'Liters Silicone Purge',
    cuttingDetails: 'CNC milled frames verified against cutting list CL-101; zero burrs on thermal break slots.',
    weldingDetails: 'N/A - Heavy hydraulic corner crimping with 2-component structural corner adhesive.',
    assemblyDetails: 'EPDM gaskets vulcanized at corners; two-part silicone bite 18mm x 8mm verified via butterfly test.',
    measurements: [
      { id: 'm-1', parameterName: 'Overall Panel Width (mm)', nominalValue: 1500, tolerancePlusMm: 1.0, toleranceMinusMm: 1.0, actualMeasuredValue: 1500.3, unit: 'mm', withinSpec: true },
      { id: 'm-2', parameterName: 'Overall Panel Height (mm)', nominalValue: 3850, tolerancePlusMm: 1.5, toleranceMinusMm: 1.5, actualMeasuredValue: 3849.8, unit: 'mm', withinSpec: true },
      { id: 'm-3', parameterName: 'Frame Diagonal Difference |D1-D2|', nominalValue: 0, tolerancePlusMm: 1.5, toleranceMinusMm: 0, actualMeasuredValue: 0.8, unit: 'mm', withinSpec: true },
      { id: 'm-4', parameterName: 'Structural Silicone Bite Width', nominalValue: 18, tolerancePlusMm: 2.0, toleranceMinusMm: 0, actualMeasuredValue: 18.6, unit: 'mm', withinSpec: true }
    ],
    inspectionResult: 'Pass',
    problemsEncountered: 'Panel #CW-039 had minor gasket corner gap; resealed immediately in shift.',
    supervisorRemarks: 'Snap-time test 28 mins (within 20-40 min spec). Cleared for curing rack.',
    completionStatus: 'QC Approved',
    audit: {
      createdBy: 'Kasun Perera',
      createdByRole: 'Glazing Supervisor',
      createdAt: '2026-09-25T15:30:00Z',
      updatedBy: 'Marcus Silva',
      updatedByRole: 'QA Lead',
      updatedAt: '2026-09-25T17:00:00Z',
      revision: 1,
      status: 'QC Approved',
      approvalHistory: [
        { stage: 'QC Sign-Off', actorName: 'Marcus Silva', actorRole: 'QA Lead', decision: 'Approved', timestamp: '2026-09-25T17:00:00Z', remarks: 'Dimensional & butterfly adhesion log verified.' }
      ]
    }
  },
  {
    id: 'dws-02',
    worksheetNo: 'DWS-2026-0090',
    activityType: 'AWS/ISO Certified Welding Log',
    projectId: 'Apex Tower Structural Glazing',
    projectName: 'Apex Tower Structural Glazing',
    factoryId: 'fac-inv-02',
    factoryName: 'Innovista Heavy Structural Steel & Welding Workshop (Peliyagoda)',
    workPackageId: 'fwp-02',
    taskId: 'ftask-103',
    taskCode: 'FO-2026-205',
    drawingNumber: 'DRW-APX-STL-04',
    drawingRevision: 'Rev D',
    recordedDate: '2026-09-25',
    shift: 'Morning Shift',
    recordedByWorkerName: 'Lalith Rodrigo',
    verifiedBySupervisorName: 'Eng. Janaka Perera',
    machineId: 'EQ-WLD-01',
    machineName: 'Fronius TransSteel 5000 Pulse Welder Bank',
    machineMeterReadingStart: 890.0,
    machineMeterReadingEnd: 898.5,
    labourHoursLogged: 28,
    plannedQtyForShift: 2,
    producedQty: 2,
    acceptedQty: 1,
    rejectedQty: 0,
    reworkQty: 1,
    materialConsumedSummary: '28m CHS 219.1x12.5mm S355J2H, 8 Gusset Nodes, 14kg ER70S-6 Filler Wire',
    wastageRecordedQty: 0.8,
    wastageUnit: 'kg Stub/Spatter',
    cuttingDetails: 'CNC plasma bevelled 37.5° V-groove root preparation with 2mm root face.',
    weldingDetails: 'WPS-AWS-D1.1-04 followed; preheat 110°C verified by digital pyrometer; interpass <220°C.',
    assemblyDetails: 'Jig-clamped spider node alignment verified with laser total station prior to root pass.',
    measurements: [
      { id: 'm-5', parameterName: 'Truss Span Center-to-Center (mm)', nominalValue: 6400, tolerancePlusMm: 2.0, toleranceMinusMm: 2.0, actualMeasuredValue: 6400.5, unit: 'mm', withinSpec: true },
      { id: 'm-6', parameterName: 'Fillet Weld Leg Size (mm)', nominalValue: 10, tolerancePlusMm: 2.0, toleranceMinusMm: 0, actualMeasuredValue: 10.8, unit: 'mm', withinSpec: true },
      { id: 'm-7', parameterName: 'Preheat Temperature (°C)', nominalValue: 100, tolerancePlusMm: 50, toleranceMinusMm: 0, actualMeasuredValue: 114, unit: '°C', withinSpec: true }
    ],
    inspectionResult: 'Rework Required',
    problemsEncountered: 'UT scan detected 4mm subsurface root porosity on Node N3 of Truss TR-09.',
    supervisorRemarks: 'Gouged and re-welded Node N3; submitted for UT reinspection.',
    completionStatus: 'Supervisor Verified',
    audit: {
      createdBy: 'Lalith Rodrigo',
      createdByRole: 'Welding Supervisor',
      createdAt: '2026-09-25T16:40:00Z',
      updatedBy: 'Eng. Janaka Perera',
      updatedByRole: 'Workshop Manager',
      updatedAt: '2026-09-25T18:00:00Z',
      revision: 1,
      status: 'Supervisor Verified',
      approvalHistory: []
    }
  }
];

export const SEED_DOCUMENTS: ControlledTechnicalDocument[] = [
  {
    id: 'cdoc-01',
    docNumber: 'DRW-SM-CW-101',
    title: 'Sirius Mall North Elevation Unitized Curtain Wall Shop & Fabrication Drawing',
    category: 'Fabrication Drawing',
    projectId: 'Sirius Mall Storefront',
    projectName: 'Sirius Mall High-Rise Curtain Wall',
    factoryId: 'fac-inv-01',
    factoryName: 'Innovista Central Facade & Curtain Wall Plant (Biyagama)',
    workPackageId: 'fwp-01',
    currentRevision: 'Rev C',
    previousRevisions: [
      { rev: 'Rev A', date: '2026-07-20', author: 'Eng. Nuwan Senanayake', notes: 'Initial tender fabrication geometry' },
      { rev: 'Rev B', date: '2026-08-05', author: 'Eng. Nuwan Senanayake', notes: 'Updated transom drainage slot dimensions' }
    ],
    approvalStatus: 'Approved for Construction (AFC)',
    technicalInstructions: 'All CNC operators must use Rev C G-code program #SBZ-SM-101C. Destroy all printed Rev B copies on shop floor.',
    fileSize: '14.8 MB (DWG / Signed PDF)',
    distributedToFactories: ['Innovista Central Facade & Curtain Wall Plant (Biyagama)', 'Guardian & EuroGlass Tempering & DGU Subcontractor Plant (Horana)'],
    workerReadConfirmations: [
      { workerName: 'Roshan Mendis', role: 'CNC Bay Supervisor', revisionConfirmed: 'Rev C', timestamp: '2026-09-20T07:30:00Z' },
      { workerName: 'Kasun Perera', role: 'Glazing Supervisor', revisionConfirmed: 'Rev C', timestamp: '2026-09-24T08:00:00Z' }
    ],
    audit: {
      createdBy: 'Eng. Nuwan Senanayake',
      createdByRole: 'Chief Engineer',
      createdAt: '2026-08-14T10:00:00Z',
      updatedBy: 'Marcus Sterling',
      updatedByRole: 'Project Manager',
      updatedAt: '2026-09-18T09:00:00Z',
      revision: 3,
      status: 'Approved for Construction (AFC)',
      approvalHistory: [
        { stage: 'Consultant & PM AFC Release', actorName: 'Marcus Sterling', actorRole: 'Project Manager', decision: 'Approved', timestamp: '2026-09-18T09:00:00Z', remarks: 'Approved for full production.' }
      ]
    }
  },
  {
    id: 'cdoc-02',
    docNumber: 'DRW-APX-STL-04',
    title: 'Apex Tower Atrium Spider Steel Truss & Cast-In Embedment Shop Drawings',
    category: 'Shop Drawing',
    projectId: 'Apex Tower Structural Glazing',
    projectName: 'Apex Tower Structural Glazing',
    factoryId: 'fac-inv-02',
    factoryName: 'Innovista Heavy Structural Steel & Welding Workshop (Peliyagoda)',
    workPackageId: 'fwp-02',
    currentRevision: 'Rev D',
    previousRevisions: [
      { rev: 'Rev C', date: '2026-08-22', author: 'Eng. Tharindu Fernando', notes: 'Added stiffener ribs at spider routel bosses' }
    ],
    approvalStatus: 'Approved for Construction (AFC)',
    technicalInstructions: 'Full penetration butt welds (CJP) required on all primary chord splices per AWS D1.1.',
    fileSize: '19.2 MB (Tekla / IFC / PDF)',
    distributedToFactories: ['Innovista Heavy Structural Steel & Welding Workshop (Peliyagoda)'],
    workerReadConfirmations: [
      { workerName: 'Lalith Rodrigo', role: 'Welding Supervisor', revisionConfirmed: 'Rev D', timestamp: '2026-09-19T08:00:00Z' }
    ],
    audit: {
      createdBy: 'Eng. Tharindu Fernando',
      createdByRole: 'Structural Engineer',
      createdAt: '2026-08-22T11:00:00Z',
      updatedBy: 'Marcus Sterling',
      updatedByRole: 'Project Manager',
      updatedAt: '2026-09-10T15:00:00Z',
      revision: 4,
      status: 'Approved for Construction (AFC)',
      approvalHistory: []
    }
  }
];

export const SEED_DAILY_REPORTS: DailyFactoryActivityReport[] = [
  {
    id: 'dfar-01',
    reportNo: 'DFAR-2026-1024',
    date: '2026-09-25',
    factoryId: 'fac-inv-01',
    factoryName: 'Innovista Central Facade & Curtain Wall Plant (Biyagama)',
    projectId: 'Sirius Mall Storefront',
    projectName: 'Sirius Mall High-Rise Curtain Wall',
    shiftSupervisor: 'Eng. Chaminda Rajapakse / Kasun Perera',
    weatherOrShopCondition: 'Indoor Cleanroom: 22.4°C, 48% Relative Humidity (Optimal for Structural Silicone)',
    plannedActivitiesSummary: 'Complete CNC milling of 15 frame sets and structural glazing of 12 unitized curtain wall panels.',
    completedActivitiesSummary: 'Completed 15 CNC frame sets (100%) and glazed 12 unitized panels (11 passed QC, 1 gasket resealed).',
    plannedUnitsToday: 27,
    completedUnitsToday: 27,
    activeWorkersCount: 42,
    totalManHours: 336,
    overtimeHours: 24,
    activeMachinesCount: 6,
    machineHoursLogged: 54,
    materialsUsedSummary: '32 Bars 6063-T6 Mullions, 12 DGU Panels, 18L Dow Corning 993 Silicone',
    delaysEncountered: 'None - Continuous shift flow maintained.',
    delayReasonCategory: 'None',
    delayDurationHours: 0,
    qualityIssuesSummary: 'Minor corner gasket alignment on Panel CW-039 rectified on the spot.',
    hseIssuesSummary: 'Zero incidents. Morning vacuum lifter suction pressure check & PPE audit 100% compliant.',
    toolboxTalkTopic: 'Safe Handling of Jumbo DGU Glass Panels & Vacuum Cup Redundancy Checks',
    measurementsSummary: 'All 12 glazed panels checked for diagonal squareness (<0.9mm) and silicone bite (18.5mm).',
    nextDayPlan: 'Glaze remaining 18 panels of Batch B4 and prepare 24 cured panels for crating & dispatch.',
    supervisorComments: 'Production ahead of schedule by 1.5 days on Sirius Mall North Elevation.',
    evidenceAttachmentIds: ['evd-01', 'evd-02'],
    status: 'Approved',
    audit: {
      createdBy: 'Kasun Perera',
      createdByRole: 'Glazing Supervisor',
      createdAt: '2026-09-25T18:15:00Z',
      updatedBy: 'Marcus Sterling',
      updatedByRole: 'Project Manager',
      updatedAt: '2026-09-25T20:00:00Z',
      revision: 1,
      status: 'Approved',
      approvalHistory: []
    }
  },
  {
    id: 'dfar-02',
    reportNo: 'DFAR-2026-1025',
    date: '2026-09-25',
    factoryId: 'fac-inv-02',
    factoryName: 'Innovista Heavy Structural Steel & Welding Workshop (Peliyagoda)',
    projectId: 'Apex Tower Structural Glazing',
    projectName: 'Apex Tower Structural Glazing',
    shiftSupervisor: 'Eng. Janaka Perera / Lalith Rodrigo',
    weatherOrShopCondition: 'Shop Floor Ambient 29°C, Fume Extraction Active across all 8 welding bays',
    plannedActivitiesSummary: 'Complete full-penetration welding of Atrium Spider Trusses TR-13 & TR-14 and shot-blasting of 30 brackets.',
    completedActivitiesSummary: 'Welded TR-13 & TR-14; shot-blasted and zinc-epoxy primed 30 embed brackets.',
    plannedUnitsToday: 32,
    completedUnitsToday: 31,
    activeWorkersCount: 34,
    totalManHours: 272,
    overtimeHours: 36,
    activeMachinesCount: 5,
    machineHoursLogged: 46,
    materialsUsedSummary: '28m S355J2H CHS Pipe, 30 HDG Embed Plates, 45L Jotun Barrier Zinc Epoxy Primer',
    delaysEncountered: '6 hours rework on Truss TR-09 Node N3 root porosity.',
    delayReasonCategory: 'Quality Rework',
    delayDurationHours: 6,
    qualityIssuesSummary: 'UT NDT flagged 4mm porosity on TR-09 Node N3; arc-air gouged, re-welded, awaiting UT retest.',
    hseIssuesSummary: 'Hot Work Permit WPT-2026-079 active; fire watch maintained.',
    toolboxTalkTopic: 'Confined Node Preheat Torch Safety & Grinding Wheel Guard Inspection',
    measurementsSummary: 'DFT primer thickness 78-85µm (Spec: 75µm min); Truss span 6400.5mm.',
    nextDayPlan: 'Complete UT retest on TR-09 and weld final 2 trusses TR-15 & TR-16.',
    supervisorComments: 'Overtime shift scheduled tonight to recover the 6-hour weld repair.',
    evidenceAttachmentIds: ['evd-03'],
    status: 'Reviewed by PM',
    audit: {
      createdBy: 'Eng. Janaka Perera',
      createdByRole: 'Workshop Manager',
      createdAt: '2026-09-25T19:00:00Z',
      updatedBy: 'Marcus Sterling',
      updatedByRole: 'Project Manager',
      updatedAt: '2026-09-25T21:10:00Z',
      revision: 1,
      status: 'Reviewed by PM',
      approvalHistory: []
    }
  }
];

export const SEED_MEDIA_EVIDENCE: MediaEvidenceRecord[] = [
  {
    id: 'evd-01',
    evidenceCode: 'EVD-2026-501',
    mediaType: 'Photograph',
    stageCategory: 'During Fabrication / Production',
    projectId: 'Sirius Mall Storefront',
    projectName: 'Sirius Mall High-Rise Curtain Wall',
    factoryId: 'fac-inv-01',
    factoryName: 'Innovista Central Facade & Curtain Wall Plant (Biyagama)',
    workPackageId: 'fwp-01',
    taskId: 'ftask-101',
    taskCode: 'WO-2026-101',
    activityName: '5-Axis CNC Mullion Transom Notch & Drainage Milling',
    capturedAt: '2026-09-24T11:20:00Z',
    gpsLocation: '6.9538° N, 79.9921° E (Biyagama Bay CNC-01)',
    capturedByName: 'Roshan Mendis',
    capturedByRole: 'CNC Supervisor',
    description: 'Laser caliper verification of 150mm curtain wall mullion transom pocket milling on Elumatec SBZ 151.',
    dimensionsVerifiedText: 'Pocket Depth: 42.02mm (Nominal 42.00mm ±0.2mm)',
    thumbnailPreviewUrl: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?auto=format&fit=crop&w=600&q=80',
    verifiedByQa: true,
    audit: {
      createdBy: 'Roshan Mendis',
      createdByRole: 'CNC Supervisor',
      createdAt: '2026-09-24T11:22:00Z',
      updatedBy: 'Marcus Silva',
      updatedByRole: 'QA Lead',
      updatedAt: '2026-09-24T14:00:00Z',
      revision: 1,
      status: 'Verified',
      approvalHistory: []
    }
  },
  {
    id: 'evd-02',
    evidenceCode: 'EVD-2026-502',
    mediaType: 'Photograph',
    stageCategory: 'QC Inspection & Testing',
    projectId: 'Sirius Mall Storefront',
    projectName: 'Sirius Mall High-Rise Curtain Wall',
    factoryId: 'fac-inv-01',
    factoryName: 'Innovista Central Facade & Curtain Wall Plant (Biyagama)',
    workPackageId: 'fwp-01',
    taskId: 'ftask-102',
    taskCode: 'JC-2026-102',
    activityName: 'ASTM E331 Dynamic Water Penetration Chamber FAT Test',
    capturedAt: '2026-09-25T14:15:00Z',
    gpsLocation: '6.9538° N, 79.9921° E (Biyagama FAT Rig)',
    capturedByName: 'Marcus Silva',
    capturedByRole: 'QA Lead',
    description: 'Unitized curtain wall mock-up & first-article panel under 600 Pa differential pressure water spray test — zero water ingress.',
    dimensionsVerifiedText: 'Pressure: 600 Pa for 15 mins • Result: ZERO Leakage',
    thumbnailPreviewUrl: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?auto=format&fit=crop&w=600&q=80',
    verifiedByQa: true,
    audit: {
      createdBy: 'Marcus Silva',
      createdByRole: 'QA Lead',
      createdAt: '2026-09-25T14:20:00Z',
      updatedBy: 'Marcus Silva',
      updatedByRole: 'QA Lead',
      updatedAt: '2026-09-25T14:20:00Z',
      revision: 1,
      status: 'Verified',
      approvalHistory: []
    }
  },
  {
    id: 'evd-03',
    evidenceCode: 'EVD-2026-503',
    mediaType: 'Thermal / NDT Image',
    stageCategory: 'QC Inspection & Testing',
    projectId: 'Apex Tower Structural Glazing',
    projectName: 'Apex Tower Structural Glazing',
    factoryId: 'fac-inv-02',
    factoryName: 'Innovista Heavy Structural Steel & Welding Workshop (Peliyagoda)',
    workPackageId: 'fwp-02',
    taskId: 'ftask-103',
    taskCode: 'FO-2026-205',
    activityName: 'Ultrasonic Phased-Array NDT Scan of Spider Truss Node Welds',
    capturedAt: '2026-09-25T15:50:00Z',
    gpsLocation: '6.9685° N, 79.8894° E (Peliyagoda Welding Bay 02)',
    capturedByName: 'David Okafor',
    capturedByRole: 'Quality Inspector',
    description: 'Ultrasonic weld scan verifying full penetration on Spider Truss TR-01 to TR-14; Node N3 on TR-09 marked for gouging & re-weld.',
    dimensionsVerifiedText: 'AWS D1.1 Class A Acceptance Criteria',
    thumbnailPreviewUrl: 'https://images.unsplash.com/photo-1504917599217-d4dc5ebe6122?auto=format&fit=crop&w=600&q=80',
    verifiedByQa: true,
    audit: {
      createdBy: 'David Okafor',
      createdByRole: 'Quality Inspector',
      createdAt: '2026-09-25T16:00:00Z',
      updatedBy: 'David Okafor',
      updatedByRole: 'Quality Inspector',
      updatedAt: '2026-09-25T16:00:00Z',
      revision: 1,
      status: 'Verified',
      approvalHistory: []
    }
  },
  {
    id: 'evd-04',
    evidenceCode: 'EVD-2026-504',
    mediaType: 'Video Walkthrough',
    stageCategory: 'Site Delivery & Installation',
    projectId: 'Sirius Mall Storefront',
    projectName: 'Sirius Mall High-Rise Curtain Wall',
    factoryId: 'fac-inv-01',
    factoryName: 'Innovista Central Facade & Curtain Wall Plant (Biyagama)',
    workPackageId: 'fwp-01',
    taskId: 'ftask-102',
    taskCode: 'JC-2026-102',
    activityName: 'North Elevation Level 05 Unitized Curtain Wall Panel Hoisting & Interlock',
    capturedAt: '2026-09-25T16:40:00Z',
    gpsLocation: 'Sirius Mall Site - Grid N4-N9 Level 05',
    capturedByName: 'Samir Al-Nasser',
    capturedByRole: 'Site Erection Supervisor',
    description: 'Spider crane & monorail hoisting of unitized panels CW-081 to CW-096 onto pre-levelled cast-in brackets.',
    dimensionsVerifiedText: 'Plumb & Line Tolerance: ±1.2mm across 15m bay',
    thumbnailPreviewUrl: 'https://images.unsplash.com/photo-1541888946425-d09bb18086f6?auto=format&fit=crop&w=600&q=80',
    verifiedByQa: true,
    audit: {
      createdBy: 'Samir Al-Nasser',
      createdByRole: 'Site Erection Supervisor',
      createdAt: '2026-09-25T16:45:00Z',
      updatedBy: 'Marcus Silva',
      updatedByRole: 'QA Lead',
      updatedAt: '2026-09-25T17:30:00Z',
      revision: 1,
      status: 'Verified',
      approvalHistory: []
    }
  }
];

export const SEED_QUALITY_INSPECTIONS: FactoryQualityInspectionRecord[] = [
  {
    id: 'finsp-01',
    inspectionNo: 'FIR-2026-301',
    inspectionType: 'Dimensional & Cutting Check',
    itpReference: 'ITP-CW-2026-01 (Clause 4.2)',
    projectId: 'Sirius Mall Storefront',
    projectName: 'Sirius Mall High-Rise Curtain Wall',
    factoryId: 'fac-inv-01',
    factoryName: 'Innovista Central Facade & Curtain Wall Plant (Biyagama)',
    workPackageId: 'fwp-01',
    taskId: 'ftask-101',
    taskCode: 'WO-2026-101',
    requestedBy: 'Roshan Mendis',
    requestDate: '2026-09-24',
    inspectorName: 'Marcus Silva',
    inspectionDate: '2026-09-24',
    qtySubmitted: 60,
    qtyApproved: 59,
    qtyRejected: 0,
    qtyReworkRequired: 1,
    checklistResults: [
      { item: 'Mullion Cut Length Tolerance', standard: '3850mm ±0.5mm (EN 12020)', measured: '3850.2mm', result: 'Pass' },
      { item: '5-Axis Drainage & Hardware Slots', standard: 'Per DRW-SM-CW-101 Rev C', measured: '100% Gauge Fit', result: 'Pass' },
      { item: 'Profile Surface Anodizing / PVDF Integrity', standard: 'Zero scratches on visible face', measured: '59 Pass, 1 polished', result: 'Pass' }
    ],
    decision: 'Approved',
    reinspectionStatus: 'Reinspected & Passed',
    clientOrConsultantSignOff: 'Eng. Tariq Al-Ghurair (Resident Engineer)',
    audit: {
      createdBy: 'Roshan Mendis',
      createdByRole: 'CNC Supervisor',
      createdAt: '2026-09-24T13:00:00Z',
      updatedBy: 'Marcus Silva',
      updatedByRole: 'QA Lead',
      updatedAt: '2026-09-24T16:00:00Z',
      revision: 1,
      status: 'Approved',
      approvalHistory: []
    }
  },
  {
    id: 'finsp-02',
    inspectionNo: 'FIR-2026-302',
    inspectionType: 'Welding & NDT Inspection',
    itpReference: 'ITP-STL-2026-04 (Clause 6.1 AWS D1.1)',
    projectId: 'Apex Tower Structural Glazing',
    projectName: 'Apex Tower Structural Glazing',
    factoryId: 'fac-inv-02',
    factoryName: 'Innovista Heavy Structural Steel & Welding Workshop (Peliyagoda)',
    workPackageId: 'fwp-02',
    taskId: 'ftask-103',
    taskCode: 'FO-2026-205',
    requestedBy: 'Lalith Rodrigo',
    requestDate: '2026-09-25',
    inspectorName: 'David Okafor',
    inspectionDate: '2026-09-25',
    qtySubmitted: 14,
    qtyApproved: 13,
    qtyRejected: 0,
    qtyReworkRequired: 1,
    checklistResults: [
      { item: 'Visual Weld Profile & Undercut Check', standard: 'AWS D1.1 Table 6.1 (<1mm undercut)', measured: '0.3mm max', result: 'Pass' },
      { item: '100% Ultrasonic Phased Array (UT) CJP Welds', standard: 'AWS D1.1 Class A', measured: '13 Pass, TR-09 Node N3 4mm porosity', result: 'Fail' },
      { item: 'Dimensional Camber & Node Pitch', standard: '±1.5mm', measured: '+0.6mm', result: 'Pass' }
    ],
    decision: 'Rework Required',
    linkedCentralNcrCode: 'NCR-2026-042',
    defectDescription: 'Subsurface root porosity (4mm cluster) detected by UT on Spider Truss TR-09 Node N3.',
    rootCause5Why: 'Temporary shielding gas draft from open bay door during root pass on Node N3.',
    correctiveActionPlan: 'Arc-air gouge defect zone, grind clean, erect wind screen around Bay 02 door, re-weld per WPS-04 and perform 100% UT retest.',
    reworkTaskId: 'ftask-103',
    reinspectionStatus: 'Pending Reinspection',
    audit: {
      createdBy: 'David Okafor',
      createdByRole: 'Quality Inspector',
      createdAt: '2026-09-25T16:30:00Z',
      updatedBy: 'David Okafor',
      updatedByRole: 'Quality Inspector',
      updatedAt: '2026-09-25T16:30:00Z',
      revision: 1,
      status: 'Rework Required',
      approvalHistory: []
    }
  },
  {
    id: 'finsp-03',
    inspectionNo: 'FIR-2026-303',
    inspectionType: 'Surface Treatment / Coating DFT',
    itpReference: 'ITP-COAT-2026-02 (Qualicoat Class 2)',
    projectId: 'Emerald Pavilion Louvre & Canopy',
    projectName: 'Emerald Pavilion Louvre & Canopy',
    factoryId: 'fac-ext-03',
    factoryName: 'Alumex & Qualicoat Architectural Coating Partner Plant (Sapugaskanda)',
    workPackageId: 'fwp-03',
    taskId: 'ftask-104',
    taskCode: 'PO-2026-308',
    requestedBy: 'Sanjeewa Dias',
    requestDate: '2026-09-25',
    inspectorName: 'Kavindi Perera',
    inspectionDate: '2026-09-25',
    qtySubmitted: 80,
    qtyApproved: 78,
    qtyRejected: 2,
    qtyReworkRequired: 0,
    checklistResults: [
      { item: 'Dry Film Thickness (DFT) Elcometer Check', standard: 'Min 40µm (3-Coat PVDF)', measured: 'Mean 43.4µm (41-46µm)', result: 'Pass' },
      { item: 'Cross-Hatch Adhesion Test (ISO 2409)', standard: 'Classification 0 (0% detachment)', measured: 'Class 0 Pass', result: 'Pass' },
      { item: 'Color Uniformity Delta-E', standard: 'Delta-E < 0.8 vs Master Sample', measured: '0.42', result: 'Pass' }
    ],
    decision: 'Approved',
    reinspectionStatus: 'Not Applicable',
    clientOrConsultantSignOff: 'Samir Khalil (Emerald Dev QA)',
    audit: {
      createdBy: 'Kavindi Perera',
      createdByRole: 'Quality Inspector',
      createdAt: '2026-09-25T15:00:00Z',
      updatedBy: 'Kavindi Perera',
      updatedByRole: 'Quality Inspector',
      updatedAt: '2026-09-25T15:10:00Z',
      revision: 1,
      status: 'Approved',
      approvalHistory: []
    }
  }
];

export const SEED_DISPATCHES: FactoryDispatchAndSiteRecord[] = [
  {
    id: 'fdsp-01',
    dispatchNo: 'DSP-2026-088',
    deliveryNoteNo: 'DN-2026-088',
    packingListNo: 'PKL-2026-088',
    projectId: 'Sirius Mall Storefront',
    projectName: 'Sirius Mall High-Rise Curtain Wall',
    factoryId: 'fac-inv-01',
    factoryName: 'Innovista Central Facade & Curtain Wall Plant (Biyagama)',
    workPackageId: 'fwp-01',
    taskIds: ['ftask-101', 'ftask-102'],
    itemDescription: 'Unitized Curtain Wall Glazed Panels (Panels CW-061 to CW-096) on Heavy Steel A-Frame Stillages',
    totalCratesOrPallets: 6,
    totalQuantityDispatched: 36,
    unit: 'Panels',
    grossWeightKg: 11880,
    qrBatchLabelCode: 'QR-SM-CW-BATCH03-088',
    packingVerifiedBy: 'Marcus Silva',
    loadingPhotoVerified: true,
    vehicleRegistrationNo: 'WP LM-4829 (40ft Low-Bed Air-Ride Trailer)',
    vehicleType: '40ft Air-Suspension Facade Carrier',
    driverName: 'bandula Jayasinghe',
    driverPhone: '+94 77 312 8840',
    dispatchDate: '2026-09-24',
    expectedSiteArrival: '2026-09-24 14:00',
    actualSiteArrival: '2026-09-24 13:45',
    siteDeliveryLocation: 'Sirius Mall Tower Hoist Zone B - North Gate',
    receivedBySiteEngineer: 'Samir Al-Nasser',
    damagedQuantity: 0,
    missingQuantity: 0,
    assignedSiteInstallationTeam: 'Facade Erection Crew Alpha (12 Riggers & Glaziers)',
    siteSupervisorName: 'Samir Al-Nasser',
    installationZoneOrElevation: 'North Elevation Level 04 & Level 05 (Grid N1-N12)',
    installedQuantity: 32,
    installationProgressPercent: 89,
    siteInspectionRef: 'WIR-SM-2026-044',
    lifecycleStage: 'Site Installation In Progress',
    audit: {
      createdBy: 'Marcus Silva',
      createdByRole: 'QA Lead',
      createdAt: '2026-09-24T09:30:00Z',
      updatedBy: 'Samir Al-Nasser',
      updatedByRole: 'Site Erection Supervisor',
      updatedAt: '2026-09-25T17:15:00Z',
      revision: 2,
      status: 'Site Installation In Progress',
      approvalHistory: [
        { stage: 'Pre-Dispatch Packing & QR Verification', actorName: 'Marcus Silva', actorRole: 'QA Lead', decision: 'Approved', timestamp: '2026-09-24T09:30:00Z', remarks: 'Foam corner protectors & A-frame ratchet straps verified.' },
        { stage: 'Site Receipt Confirmation', actorName: 'Samir Al-Nasser', actorRole: 'Site Erection Supervisor', decision: 'Verified', timestamp: '2026-09-24T13:55:00Z', remarks: 'All 36 panels received undamaged.' }
      ]
    }
  },
  {
    id: 'fdsp-02',
    dispatchNo: 'DSP-2026-089',
    deliveryNoteNo: 'DN-2026-089',
    packingListNo: 'PKL-2026-089',
    projectId: 'Emerald Pavilion Louvre & Canopy',
    projectName: 'Emerald Pavilion Louvre & Canopy',
    factoryId: 'fac-ext-03',
    factoryName: 'Alumex & Qualicoat Architectural Coating Partner Plant (Sapugaskanda)',
    workPackageId: 'fwp-03',
    taskIds: ['ftask-104'],
    itemDescription: 'PVDF Champagne Gold Coated Aerofoil Louvres & A2 Fire-Rated ACP Cassettes (Lot 2)',
    totalCratesOrPallets: 8,
    totalQuantityDispatched: 120,
    unit: 'Cassettes',
    grossWeightKg: 4650,
    qrBatchLabelCode: 'QR-EMR-ACP-LOT02-089',
    packingVerifiedBy: 'Kavindi Perera',
    loadingPhotoVerified: true,
    vehicleRegistrationNo: 'WP LD-9104 (20ft Covered Box Truck)',
    vehicleType: '20ft Enclosed Cushion Truck',
    driverName: 'Chamara Perera',
    driverPhone: '+94 71 840 2219',
    dispatchDate: '2026-09-25',
    expectedSiteArrival: '2026-09-25 16:30',
    actualSiteArrival: '2026-09-25 16:15',
    siteDeliveryLocation: 'Emerald Pavilion Laydown Yard C',
    receivedBySiteEngineer: 'Eng. Nuwan Senanayake',
    damagedQuantity: 1,
    missingQuantity: 0,
    damageRemarks: '1 cassette (ACP-C-088) had minor forklift corner dent on return flange; logged for replacement.',
    assignedSiteInstallationTeam: 'Cladding & Canopy Crew Bravo (8 Installers)',
    siteSupervisorName: 'Pradeep Kumara',
    installationZoneOrElevation: 'Main Canopy Soffit & East Retail Colonnade',
    installedQuantity: 119,
    installationProgressPercent: 99,
    siteInspectionRef: 'WIR-EMR-2026-019',
    clientAcceptanceCertificateNo: 'CAC-EMR-2026-02',
    lifecycleStage: 'Client Accepted & Handed Over',
    audit: {
      createdBy: 'Sanjeewa Dias',
      createdByRole: 'Partner Operations Director',
      createdAt: '2026-09-25T11:00:00Z',
      updatedBy: 'Marcus Sterling',
      updatedByRole: 'Project Manager',
      updatedAt: '2026-09-26T04:00:00Z',
      revision: 3,
      status: 'Client Accepted & Handed Over',
      approvalHistory: [
        { stage: 'Client & PM Acceptance Sign-Off', actorName: 'Marcus Sterling', actorRole: 'Project Manager', decision: 'Approved', timestamp: '2026-09-26T04:00:00Z', remarks: '119 installed cassettes accepted by client; 1 replacement scheduled.' }
      ]
    }
  }
];

export const SEED_APPROVAL_RULES: FactoryApprovalMatrixRule[] = [
  {
    id: 'apr-01',
    ruleCode: 'MAT-RULE-01',
    name: 'Critical Path Work Package Assignment & Budget Release (> LKR 25M)',
    projectScope: 'All Projects',
    factoryOwnershipScope: 'All Factory Types',
    minWorkValueThreshold: 25000000,
    taskOrStageTrigger: 'Draft → Assigned / Planned',
    requiredApproverRoles: ['Project Manager', 'Plant Director / Workshop Manager', 'Super Administrator'],
    slaHours: 12,
    mandatoryQualityHoldPoint: false,
    active: true
  },
  {
    id: 'apr-02',
    ruleCode: 'MAT-RULE-02',
    name: 'Pre-Dispatch Factory Acceptance Test (FAT) & Quality Release Gate',
    projectScope: 'All Projects',
    factoryOwnershipScope: 'All Factory Types',
    minWorkValueThreshold: 0,
    taskOrStageTrigger: 'Submitted for Inspection → Approved → Packed',
    requiredApproverRoles: ['Quality Inspector / QA Lead', 'Factory Manager'],
    slaHours: 6,
    mandatoryQualityHoldPoint: true,
    active: true
  },
  {
    id: 'apr-03',
    ruleCode: 'MAT-RULE-03',
    name: 'External Partner / Subcontractor Completion & Progress Valuation Approval',
    projectScope: 'All Projects',
    factoryOwnershipScope: 'Strategic Partner',
    minWorkValueThreshold: 5000000,
    taskOrStageTrigger: 'Delivered / Installed → Accepted → Closed',
    requiredApproverRoles: ['Quality Inspector', 'Quantity Surveyor (QS)', 'Project Manager'],
    slaHours: 24,
    mandatoryQualityHoldPoint: true,
    active: true
  }
];

export const SEED_GENERATED_DOCS: GeneratedFactoryDocument[] = [
  {
    id: 'gdoc-01',
    docControlNo: 'DOC-WO-2026-101',
    docType: 'Work Order (WO)',
    title: 'Work Order WO-2026-101: 5-Axis CNC Milling & Cutting (Batch B4)',
    projectId: 'Sirius Mall Storefront',
    projectName: 'Sirius Mall High-Rise Curtain Wall',
    factoryId: 'fac-inv-01',
    factoryName: 'Innovista Central Facade & Curtain Wall Plant (Biyagama)',
    workPackageCode: 'FWP-2026-001',
    taskCode: 'WO-2026-101',
    generatedBy: 'Eng. Nuwan Senanayake',
    generatedAt: '2026-09-18T07:00:00Z',
    revision: 'Rev C',
    status: 'Approved',
    summaryData: { PlannedQty: '60 Frame Sets', CompletedQty: '60 Frame Sets', Drawing: 'DRW-SM-CW-101 Rev C', Machine: 'Elumatec SBZ 151' }
  },
  {
    id: 'gdoc-02',
    docControlNo: 'DOC-FAC-2026-088',
    docType: 'Factory Acceptance Certificate (FAC)',
    title: 'Factory Acceptance Certificate: Sirius Mall Unitized Panels CW-061 to CW-096',
    projectId: 'Sirius Mall Storefront',
    projectName: 'Sirius Mall High-Rise Curtain Wall',
    factoryId: 'fac-inv-01',
    factoryName: 'Innovista Central Facade & Curtain Wall Plant (Biyagama)',
    workPackageCode: 'FWP-2026-001',
    taskCode: 'JC-2026-102',
    generatedBy: 'Marcus Silva',
    generatedAt: '2026-09-24T09:00:00Z',
    revision: 'Rev A',
    status: 'Signed-Off',
    summaryData: { BatchSize: '36 Panels', WaterRigTest: '600 Pa Zero Leak', SiliconeBite: '18.6mm Pass', Inspector: 'Marcus Silva' }
  },
  {
    id: 'gdoc-03',
    docControlNo: 'DOC-DN-2026-088',
    docType: 'Site Delivery Note (DN)',
    title: 'Delivery Note DN-2026-088: 36 Unitized Curtain Wall Panels to Sirius Mall Site',
    projectId: 'Sirius Mall Storefront',
    projectName: 'Sirius Mall High-Rise Curtain Wall',
    factoryId: 'fac-inv-01',
    factoryName: 'Innovista Central Facade & Curtain Wall Plant (Biyagama)',
    workPackageCode: 'FWP-2026-001',
    taskCode: 'JC-2026-102',
    generatedBy: 'Marcus Silva',
    generatedAt: '2026-09-24T09:45:00Z',
    revision: 'Rev A',
    status: 'Signed-Off',
    summaryData: { Vehicle: 'WP LM-4829', Crates: '6 A-Frame Stillages', GrossWeight: '11,880 kg', SiteReceiver: 'Samir Al-Nasser' }
  }
];

export const SEED_OFFLINE_QUEUE: OfflineSyncQueueItem[] = [
  {
    id: 'off-01',
    recordType: 'Task Progress',
    factoryName: 'Innovista Heavy Structural Steel & Welding Workshop (Peliyagoda)',
    taskCode: 'FO-2026-205',
    summary: 'Mobile Offline Log: Truss TR-14 root & hot pass completed (4.5 hrs logged, preheat 112°C)',
    capturedBy: 'Lalith Rodrigo (Mobile Tablet #04)',
    capturedAtOffline: '2026-09-26T06:10:00Z',
    syncStatus: 'Queued (Offline)',
    payload: { taskId: 'ftask-103', deltaCompleted: 1, hours: 4.5 }
  }
];
