import {
  FactoryMasterProfile,
  FactoryWorkPackageAssignment
} from '../types/factoryPortal';

export const SEED_FACTORIES: FactoryMasterProfile[] = [
  {
    id: 'fac-inv-01',
    factoryCode: 'FAC-INV-01',
    name: 'Innovista Central Facade & Curtain Wall Plant (Biyagama)',
    facilityType: 'Integrated Facade & Curtain Wall Plant',
    ownershipType: 'Innovista Owned',
    partnerRelationshipTier: 'Core Internal',
    status: 'Active',
    address: 'Block B-14, Biyagama Export Processing Zone, Western Province',
    city: 'Colombo / Biyagama',
    country: 'Sri Lanka',
    gpsCoordinates: '6.9538° N, 79.9921° E',
    primaryContactPerson: 'Eng. Chaminda Rajapakse',
    primaryContactRole: 'Plant Director',
    contactPhone: '+94 11 246 5800',
    contactEmail: 'chaminda.plant@innovista.com',
    factoryManagerName: 'Eng. Chaminda Rajapakse',
    chiefEngineerName: 'Eng. Nuwan Senanayake',
    qaLeadName: 'Marcus Silva',
    hseOfficerName: 'Dinesh Jayawardena',
    operatingAreas: ['Unitized Curtain Wall Line A', '5-Axis CNC Milling Hall', 'Structural Silicone Cleanroom', 'FAT Water Test Rig'],
    capabilities: [
      'Aluminium Fabrication',
      'CNC Machining & Milling',
      'Unitized Curtain Wall Assembly',
      'Structural Glazing & Silicone',
      'Double Glazing (DGU) Assembly',
      'ACP Routing & Folding',
      'Heavy Crating & Export Packaging',
      'Site Erection & Glazing Installation'
    ],
    materialsHandled: ['6063-T6 Aluminium Extrusions', '24mm Low-E DGU Glass', 'Dow Corning 993 Structural Silicone', 'EPDM Gaskets', '4mm FR ACP Sheets'],
    productsManufactured: ['Unitized Curtain Wall Panels', 'Spider Glazing Assemblies', 'Thermal-Break Sliding Doors', 'Bespoke Louvres & Sunshades'],
    fabricationTypes: ['CNC 5-Axis Profile Machining', 'Crimped Corner Assembly', 'Two-Part Structural Glazing', 'Unitized Panel Cassette Assembly'],
    maximumCapacityUnitsPerMonth: 6500,
    monthlyCapacityTonnesOrSqm: 5800,
    capacityUnitLabel: 'm²',
    currentCapacityUtilization: 84,
    standardLeadTimeDays: 14,
    workingShifts: [
      { shiftName: 'Morning Shift A', hours: '07:00 - 15:30', activeWorkers: 42 },
      { shiftName: 'Evening Shift B', hours: '15:30 - 00:00', activeWorkers: 24 }
    ],
    workingHoursPerDay: 16,
    workingDaysPerWeek: 6,
    holidaysCalendar: ['2026-04-13', '2026-04-14', '2026-05-01'],
    certifications: [
      { code: 'ISO 9001:2015 QMS', issuer: 'SGS United Kingdom', expiryDate: '2028-06-30', status: 'Valid' },
      { code: 'ISO 45001:2018 OH&S', issuer: 'BSI Group', expiryDate: '2027-11-15', status: 'Valid' },
      { code: 'CWCT Curtain Wall Testing Cert', issuer: 'CWCT Bath', expiryDate: '2027-08-20', status: 'Valid' }
    ],
    tradeLicenseNo: 'BOI-SL-2019-8841',
    licenseExpiryDate: '2027-12-31',
    insurancePolicyNo: 'ALLIANZ-IND-99420',
    insuranceCoverageAmount: 250000000,
    insuranceExpiryDate: '2027-03-31',
    safetyRequirements: ['Mandatory Safety Shoes & Eye Protection', 'Vacuum Lifter Daily Load Check', 'Silicone Cleanroom Ventilation Monitoring'],
    qualityCapabilities: ['In-House Air/Water Infiltration Rig (ASTM E331)', 'Webster Hardness & Micron DFT Testing', 'Laser Diagonal Verification'],
    productionAreas: [
      { id: 'pa-01', code: 'BAY-CNC-01', name: '5-Axis CNC & Double Mitre Cutting Bay', areaSqm: 1200, bayType: 'Cutting', supervisorName: 'Roshan Mendis', maxConcurrentWorkOrders: 8, activeWorkOrdersCount: 7, utilizationPercent: 88 },
      { id: 'pa-02', code: 'BAY-ASM-02', name: 'Unitized Curtain Wall Assembly Line', areaSqm: 2400, bayType: 'Assembly', supervisorName: 'Pradeep Kumara', maxConcurrentWorkOrders: 10, activeWorkOrdersCount: 8, utilizationPercent: 82 },
      { id: 'pa-03', code: 'BAY-GLZ-03', name: 'Climate-Controlled Structural Glazing Room', areaSqm: 950, bayType: 'Glazing', supervisorName: 'Kasun Perera', maxConcurrentWorkOrders: 6, activeWorkOrdersCount: 5, utilizationPercent: 83 },
      { id: 'pa-04', code: 'BAY-FAT-04', name: 'QA/QC Inspection & Crating Dispatch Yard', areaSqm: 1100, bayType: 'Packing & Dispatch', supervisorName: 'Marcus Silva', maxConcurrentWorkOrders: 8, activeWorkOrdersCount: 6, utilizationPercent: 75 }
    ],
    storageAreas: [
      { name: 'Cantilever Extrusion Rack Zone A', type: 'Raw Profile Rack', capacityStatus: '78% Full (48 Tonnes)' },
      { name: 'Heavy DGU Glass A-Frame Vault', type: 'Glass A-Frame Bay', capacityStatus: '64% Full (320 Panels)' },
      { name: 'Temp-Controlled Sealant & Silicone Store', type: 'Chemical & Paint Store', capacityStatus: 'Optimal (21°C / 45% RH)' }
    ],
    linkedProjectIds: ['Sirius Mall Storefront', 'Apex Tower Structural Glazing', 'Emerald Pavilion Louvre & Canopy'],
    assignedEmployeeIds: ['emp-001', 'emp-002', 'emp-003', 'emp-004'],
    assignedMachineIds: ['EQ-CNC-01', 'EQ-SAW-02', 'EQ-CRN-01'],
    assignedVehicleIds: ['VEH-FLT-01', 'VEH-TRK-02'],
    performanceScorecard: {
      overallScore: 95.4,
      onTimeCompletionRate: 96.2,
      productivityIndex: 94.0,
      qualityAcceptanceRate: 98.1,
      rejectionRate: 1.9,
      reworkRate: 2.1,
      defectRatePerUnit: 0.018,
      deliveryPerformanceRate: 97.5,
      avgResponseTimeHours: 2.4,
      capacityUtilizationRate: 84.0,
      labourProductivityRate: 93.5,
      machineUtilizationRate: 86.2,
      materialWastagePercent: 2.8,
      safetyComplianceRate: 99.2,
      documentationComplianceRate: 98.5,
      historicalCompletedValue: 184500000
    },
    audit: {
      createdBy: 'Alexander Vance',
      createdByRole: 'Super Administrator',
      createdAt: '2025-01-10T08:00:00Z',
      updatedBy: 'Eng. Chaminda Rajapakse',
      updatedByRole: 'Plant Director',
      updatedAt: '2026-09-25T16:30:00Z',
      revision: 4,
      status: 'Approved',
      approvalHistory: [
        { stage: 'Registration & Audit', actorName: 'Alexander Vance', actorRole: 'Super Administrator', decision: 'Approved', timestamp: '2025-01-10T08:00:00Z', remarks: 'Core Innovista Plant commissioned.' }
      ]
    }
  },
  {
    id: 'fac-inv-02',
    factoryCode: 'FAC-INV-02',
    name: 'Innovista Heavy Structural Steel & Welding Workshop (Peliyagoda)',
    facilityType: 'Structural Steel & Heavy Welding Factory',
    ownershipType: 'Innovista Owned',
    partnerRelationshipTier: 'Core Internal',
    status: 'High Load',
    address: 'No. 412, Negombo Road, Peliyagoda Industrial Corridor',
    city: 'Peliyagoda',
    country: 'Sri Lanka',
    gpsCoordinates: '6.9685° N, 79.8894° E',
    primaryContactPerson: 'Eng. Janaka Perera',
    primaryContactRole: 'Workshop Manager',
    contactPhone: '+94 11 291 4420',
    contactEmail: 'janaka.steel@innovista.com',
    factoryManagerName: 'Eng. Janaka Perera',
    chiefEngineerName: 'Eng. Tharindu Fernando',
    qaLeadName: 'David Okafor',
    hseOfficerName: 'Nalin Bandara',
    operatingAreas: ['CNC Plasma & Laser Plate Cutting', 'AWS D1.1 Heavy Welding Bay', 'Shot Blasting & Epoxy Primer Booth'],
    capabilities: [
      'Steel Fabrication',
      'Structural Welding (AWS/ISO)',
      'CNC Machining & Milling',
      'Spray Painting & PVDF Coating',
      'Heavy Crating & Export Packaging',
      'Site Erection & Glazing Installation'
    ],
    materialsHandled: ['S355JR Structural Steel Beams', 'Hot-Dip Galvanized Embed Plates', 'SS316 Spider Routels & Brackets', 'Zinc-Rich Epoxy Primer'],
    productsManufactured: ['Curtain Wall Steel Sub-Frames', 'Canopy Trusses & Space Frames', 'Heavy Cast-In Embedment Channels', 'Architectural Steel Staircases'],
    fabricationTypes: ['MIG/TIG/SAW Structural Welding', 'CNC Plasma Profiling', 'Grit Blasting SA 2.5', 'Hot-Dip Galvanizing Coordination'],
    maximumCapacityUnitsPerMonth: 450,
    monthlyCapacityTonnesOrSqm: 380,
    capacityUnitLabel: 'Tonnes',
    currentCapacityUtilization: 91,
    standardLeadTimeDays: 18,
    workingShifts: [
      { shiftName: 'Day Shift', hours: '07:30 - 17:00', activeWorkers: 34 },
      { shiftName: 'Overtime / Night Fabrication', hours: '17:00 - 23:00', activeWorkers: 18 }
    ],
    workingHoursPerDay: 15,
    workingDaysPerWeek: 6,
    holidaysCalendar: ['2026-04-13', '2026-04-14'],
    certifications: [
      { code: 'AWS D1.1 Structural Welding', issuer: 'American Welding Society', expiryDate: '2027-09-30', status: 'Valid' },
      { code: 'EN 1090-2 EXC3 Steel Execution', issuer: 'TUV Rheinland', expiryDate: '2028-01-15', status: 'Valid' }
    ],
    tradeLicenseNo: 'IND-WP-44219',
    licenseExpiryDate: '2027-06-30',
    insurancePolicyNo: 'CEYLINCO-HVY-3310',
    insuranceCoverageAmount: 160000000,
    insuranceExpiryDate: '2027-05-15',
    safetyRequirements: ['Hot Work Permit Mandatory', 'Fume Extraction Hoods Active', '100% Ultrasonic / MPI Weld Check'],
    qualityCapabilities: ['Ultrasonic Weld Flaw Detection (UT)', 'Magnetic Particle Inspection (MPI)', 'Elcometer Wet/Dry Film Thickness'],
    productionAreas: [
      { id: 'pa-201', code: 'BAY-PLS-01', name: 'CNC Plasma & Plate Drilling Line', areaSqm: 900, bayType: 'Cutting', supervisorName: 'Saman Kumara', maxConcurrentWorkOrders: 6, activeWorkOrdersCount: 6, utilizationPercent: 95 },
      { id: 'pa-202', code: 'BAY-WLD-02', name: 'Heavy Truss & Bracket Welding Hall', areaSqm: 1800, bayType: 'Welding', supervisorName: 'Lalith Rodrigo', maxConcurrentWorkOrders: 12, activeWorkOrdersCount: 11, utilizationPercent: 92 },
      { id: 'pa-203', code: 'BAY-PNT-03', name: 'Blasting & Two-Pack Epoxy Coating Bay', areaSqm: 650, bayType: 'Coating', supervisorName: 'Ajith Perera', maxConcurrentWorkOrders: 5, activeWorkOrdersCount: 4, utilizationPercent: 80 }
    ],
    storageAreas: [
      { name: 'Gantry Crane Steel Stockyard', type: 'Raw Profile Rack', capacityStatus: '85% Full (210 Tonnes)' },
      { name: 'Coated Brackets Dispatch Bay', type: 'Crated Dispatch Yard', capacityStatus: '72% Full' }
    ],
    linkedProjectIds: ['Apex Tower Structural Glazing', 'Emerald Pavilion Louvre & Canopy'],
    assignedEmployeeIds: ['emp-002', 'emp-005'],
    assignedMachineIds: ['EQ-WLD-01', 'EQ-CRN-02'],
    assignedVehicleIds: ['VEH-TRK-01'],
    performanceScorecard: {
      overallScore: 92.8,
      onTimeCompletionRate: 93.5,
      productivityIndex: 91.8,
      qualityAcceptanceRate: 96.9,
      rejectionRate: 3.1,
      reworkRate: 2.8,
      defectRatePerUnit: 0.024,
      deliveryPerformanceRate: 94.2,
      avgResponseTimeHours: 3.1,
      capacityUtilizationRate: 91.0,
      labourProductivityRate: 92.0,
      machineUtilizationRate: 89.5,
      materialWastagePercent: 3.4,
      safetyComplianceRate: 98.5,
      documentationComplianceRate: 96.0,
      historicalCompletedValue: 112000000
    },
    audit: {
      createdBy: 'Alexander Vance',
      createdByRole: 'Super Administrator',
      createdAt: '2025-02-01T08:00:00Z',
      updatedBy: 'Eng. Janaka Perera',
      updatedByRole: 'Workshop Manager',
      updatedAt: '2026-09-24T14:20:00Z',
      revision: 3,
      status: 'Approved',
      approvalHistory: [
        { stage: 'Registration', actorName: 'Alexander Vance', actorRole: 'Super Administrator', decision: 'Approved', timestamp: '2025-02-01T08:00:00Z', remarks: 'Heavy structural steel division registered.' }
      ]
    }
  },
  {
    id: 'fac-ext-03',
    factoryCode: 'FAC-PARTNER-03',
    name: 'Alumex & Qualicoat Architectural Coating Partner Plant (Sapugaskanda)',
    facilityType: 'Powder Coating & Surface Treatment Plant',
    ownershipType: 'Strategic Partner',
    linkedSupplierId: 'sup-002',
    partnerRelationshipTier: 'Tier-1 Strategic Partner',
    status: 'Active',
    address: 'Pattiwila Road, Sapugaskanda Industrial Estate, Makola',
    city: 'Sapugaskanda',
    country: 'Sri Lanka',
    gpsCoordinates: '6.9642° N, 79.9573° E',
    primaryContactPerson: 'Christian Moreau / Sanjeewa Dias',
    primaryContactRole: 'Partner Operations Director',
    contactPhone: '+94 11 240 0332',
    contactEmail: 'operations@alumex-partner.lk',
    factoryManagerName: 'Sanjeewa Dias',
    chiefEngineerName: 'Eng. Malintha Silva',
    qaLeadName: 'Kavindi Perera',
    hseOfficerName: 'Rohan Wijesinghe',
    operatingAreas: ['Vertical Powder Coating Line', 'PVDF 3-Coat Fluorocarbon Line', 'Wood-Grain Sublimation Line', 'ACP Cassette CNC Cell'],
    capabilities: [
      'Powder Coating & Anodizing',
      'Spray Painting & PVDF Coating',
      'ACP Routing & Folding',
      'Aluminium Fabrication',
      'Heavy Crating & Export Packaging'
    ],
    materialsHandled: ['Jotun Super Durable Powder', 'PPG Duranar PVDF Resin', 'Alucobond A2 4mm Core Sheets', 'Architectural Mill Finish Profiles'],
    productsManufactured: ['PVDF Coated Curtain Wall Mullions', 'Fire-Rated ACP Cladding Cassettes', 'Anodized Architectural Louvres'],
    fabricationTypes: ['Chromate-Free Pre-Treatment', 'Electrostatic Powder Application', 'CNC V-Grooving & Cassette Folding'],
    maximumCapacityUnitsPerMonth: 9000,
    monthlyCapacityTonnesOrSqm: 7500,
    capacityUnitLabel: 'm²',
    currentCapacityUtilization: 72,
    standardLeadTimeDays: 10,
    workingShifts: [
      { shiftName: 'Continuous Line Shift 1', hours: '06:00 - 14:00', activeWorkers: 28 },
      { shiftName: 'Continuous Line Shift 2', hours: '14:00 - 22:00', activeWorkers: 26 }
    ],
    workingHoursPerDay: 16,
    workingDaysPerWeek: 6,
    holidaysCalendar: ['2026-05-01'],
    certifications: [
      { code: 'Qualicoat Seaside Class 2', issuer: 'Qualicoat Zurich', expiryDate: '2027-12-31', status: 'Valid' },
      { code: 'Qualanod Architectural Anodizing', issuer: 'Qualanod', expiryDate: '2027-10-15', status: 'Valid' }
    ],
    tradeLicenseNo: 'EXT-PARTNER-9012',
    licenseExpiryDate: '2028-03-31',
    insurancePolicyNo: 'FAIRFIRST-PRT-7721',
    insuranceCoverageAmount: 180000000,
    insuranceExpiryDate: '2027-08-30',
    safetyRequirements: ['Chemical Bath Neutralization Monitoring', 'Electrostatic Booth Earthing Check'],
    qualityCapabilities: ['Cross-Hatch Adhesion (ISO 2409)', 'Salt Spray Chamber (1000 hrs)', 'Colorimeter Delta-E Spectrophotometer'],
    productionAreas: [
      { id: 'pa-301', code: 'BAY-PVDF-01', name: 'Vertical PVDF & Powder Coating Tunnel', areaSqm: 2100, bayType: 'Coating', supervisorName: 'Nimal Siripala', maxConcurrentWorkOrders: 10, activeWorkOrdersCount: 7, utilizationPercent: 70 },
      { id: 'pa-302', code: 'BAY-ACP-02', name: '3D CNC ACP Routing & Cassette Folding Cell', areaSqm: 1150, bayType: 'Machining', supervisorName: 'Chathura Alwis', maxConcurrentWorkOrders: 8, activeWorkOrdersCount: 6, utilizationPercent: 75 }
    ],
    storageAreas: [
      { name: 'Protective Taped Profile Dispatch Rack', type: 'Crated Dispatch Yard', capacityStatus: '61% Full' }
    ],
    linkedProjectIds: ['Sirius Mall Storefront', 'Emerald Pavilion Louvre & Canopy'],
    assignedEmployeeIds: ['emp-003'],
    assignedMachineIds: ['EQ-CNC-02'],
    assignedVehicleIds: ['VEH-TRK-02'],
    performanceScorecard: {
      overallScore: 94.1,
      onTimeCompletionRate: 95.0,
      productivityIndex: 93.2,
      qualityAcceptanceRate: 97.6,
      rejectionRate: 2.4,
      reworkRate: 1.8,
      defectRatePerUnit: 0.015,
      deliveryPerformanceRate: 96.0,
      avgResponseTimeHours: 4.0,
      capacityUtilizationRate: 72.0,
      labourProductivityRate: 91.5,
      machineUtilizationRate: 79.0,
      materialWastagePercent: 2.1,
      safetyComplianceRate: 97.8,
      documentationComplianceRate: 95.5,
      historicalCompletedValue: 96400000
    },
    audit: {
      createdBy: 'Tariq Mansoor',
      createdByRole: 'Procurement Director',
      createdAt: '2025-03-12T09:30:00Z',
      updatedBy: 'Marcus Sterling',
      updatedByRole: 'Project Manager',
      updatedAt: '2026-09-23T11:00:00Z',
      revision: 2,
      status: 'Approved',
      approvalHistory: [
        { stage: 'Partner Qualification', actorName: 'Tariq Mansoor', actorRole: 'Procurement Director', decision: 'Approved', timestamp: '2025-03-12T09:30:00Z', remarks: 'Qualicoat Class 2 verified.' }
      ]
    }
  },
  {
    id: 'fac-ext-04',
    factoryCode: 'FAC-SUB-04',
    name: 'Guardian & EuroGlass Tempering & DGU Subcontractor Plant (Horana)',
    facilityType: 'Architectural Glass Processing Plant',
    ownershipType: 'External Fabricator',
    linkedSupplierId: 'sup-003',
    partnerRelationshipTier: 'Specialist Fabricator',
    status: 'Active',
    address: 'Horana Industrial Park, Zone C, Kalutara District',
    city: 'Horana',
    country: 'Sri Lanka',
    gpsCoordinates: '6.7156° N, 80.0628° E',
    primaryContactPerson: 'Vikramjit Singh',
    primaryContactRole: 'Plant General Manager',
    contactPhone: '+94 34 226 1900',
    contactEmail: 'vikram@euroglass-sub.lk',
    factoryManagerName: 'Vikramjit Singh',
    chiefEngineerName: 'Eng. Ashan Gunawardena',
    qaLeadName: 'Marcus Silva',
    hseOfficerName: 'Sunil Perera',
    operatingAreas: ['CNC Glass Cutting Table', 'Convection Tempering Furnace', 'Automated Argon DGU Line', 'PVB Autoclave Lamination'],
    capabilities: [
      'Glass Cutting & Tempering',
      'Double Glazing (DGU) Assembly',
      'Structural Glazing & Silicone',
      'Heavy Crating & Export Packaging'
    ],
    materialsHandled: ['10mm Solar Control Low-E Float Glass', '1.52mm SentryGlas / PVB Interlayer', 'Warm-Edge Spacer Bars', 'Secondary Polysulfide/Silicone Sealant'],
    productsManufactured: ['28mm Double Glazed Insulated Units', '13.52mm Tempered Laminated Canopy Glass', 'Ceramic Fritted Spandrel Glass'],
    fabricationTypes: ['CNC Edge Deletion & Arrissing', 'Horizontal Roller-Hearth Tempering', 'Argon Gas Filling & Secondary Sealing'],
    maximumCapacityUnitsPerMonth: 5200,
    monthlyCapacityTonnesOrSqm: 4800,
    capacityUnitLabel: 'm²',
    currentCapacityUtilization: 68,
    standardLeadTimeDays: 12,
    workingShifts: [
      { shiftName: 'Furnace Shift Day', hours: '07:00 - 19:00', activeWorkers: 30 }
    ],
    workingHoursPerDay: 12,
    workingDaysPerWeek: 6,
    holidaysCalendar: ['2026-04-13', '2026-04-14'],
    certifications: [
      { code: 'EN 12150 Thermally Toughened Safety Glass', issuer: 'IFT Rosenheim', expiryDate: '2028-02-28', status: 'Valid' },
      { code: 'EN 1279 Insulating Glass Units', issuer: 'TUV SUD', expiryDate: '2027-07-31', status: 'Valid' }
    ],
    tradeLicenseNo: 'SUB-GLS-6610',
    licenseExpiryDate: '2027-12-31',
    insurancePolicyNo: 'SRILANKA-INS-4091',
    insuranceCoverageAmount: 125000000,
    insuranceExpiryDate: '2027-04-30',
    safetyRequirements: ['Cut-Resistant Kevlar Sleeves & Gloves Level 5', 'Overhead Vacuum Frame Redundancy'],
    qualityCapabilities: ['Zebra Board Optical Roller Wave Check', 'Fragmentation Particle Count (EN 12150)', 'Argon Gas Concentration Analyzer'],
    productionAreas: [
      { id: 'pa-401', code: 'BAY-TMP-01', name: 'CNC Cutting, Edging & Tempering Furnace', areaSqm: 1650, bayType: 'Glazing', supervisorName: 'Ramesh Kumar', maxConcurrentWorkOrders: 8, activeWorkOrdersCount: 5, utilizationPercent: 65 },
      { id: 'pa-402', code: 'BAY-DGU-02', name: 'Automated Insulated Glass (DGU) Assembly Line', areaSqm: 1400, bayType: 'Assembly', supervisorName: 'Dilantha Perera', maxConcurrentWorkOrders: 6, activeWorkOrdersCount: 4, utilizationPercent: 71 }
    ],
    storageAreas: [
      { name: 'Jumbo Float Glass Tilt-Table Bay', type: 'Glass A-Frame Bay', capacityStatus: '70% Full' }
    ],
    linkedProjectIds: ['Sirius Mall Storefront', 'Apex Tower Structural Glazing'],
    assignedEmployeeIds: ['emp-004'],
    assignedMachineIds: [],
    assignedVehicleIds: [],
    performanceScorecard: {
      overallScore: 91.5,
      onTimeCompletionRate: 92.4,
      productivityIndex: 90.5,
      qualityAcceptanceRate: 96.2,
      rejectionRate: 3.8,
      reworkRate: 2.2,
      defectRatePerUnit: 0.021,
      deliveryPerformanceRate: 93.8,
      avgResponseTimeHours: 5.5,
      capacityUtilizationRate: 68.0,
      labourProductivityRate: 89.4,
      machineUtilizationRate: 82.0,
      materialWastagePercent: 4.1,
      safetyComplianceRate: 98.0,
      documentationComplianceRate: 94.0,
      historicalCompletedValue: 74800000
    },
    audit: {
      createdBy: 'Tariq Mansoor',
      createdByRole: 'Procurement Director',
      createdAt: '2025-04-05T10:00:00Z',
      updatedBy: 'David Okafor',
      updatedByRole: 'Quality Inspector',
      updatedAt: '2026-09-22T09:15:00Z',
      revision: 2,
      status: 'Approved',
      approvalHistory: [
        { stage: 'Technical QA Audit', actorName: 'David Okafor', actorRole: 'Quality Inspector', decision: 'Approved', timestamp: '2025-04-05T10:00:00Z', remarks: 'Furnace anisotropy & fragmentation verified.' }
      ]
    }
  }
];

export const SEED_WORK_PACKAGES: FactoryWorkPackageAssignment[] = [
  {
    id: 'fwp-01',
    packageCode: 'FWP-2026-001',
    projectId: 'Sirius Mall Storefront',
    projectName: 'Sirius Mall High-Rise Curtain Wall',
    factoryId: 'fac-inv-01',
    factoryName: 'Innovista Central Facade & Curtain Wall Plant (Biyagama)',
    ownershipType: 'Innovista Owned',
    title: 'North & East Elevation Unitized Curtain Wall Panels (L1-L8)',
    scopeDescription: 'Complete 5-axis CNC machining, thermal-break assembly, structural silicone glazing, and water-rig FAT testing of 180 unitized curtain wall panels.',
    boqReferenceCodes: ['BOQ-CW-101', 'BOQ-CW-102'],
    drawingNumbers: ['DRW-SM-CW-101 Rev C', 'DRW-SM-CW-102 Rev B'],
    specificationCodes: ['SPEC-ALU-6063-T6', 'SPEC-GLS-DGU28'],
    methodStatementCode: 'MOS-FAB-CW-01',
    itpPlanCode: 'ITP-CW-2026-01',
    plannedQuantity: 180,
    completedQuantity: 142,
    rejectedQuantity: 3,
    reworkQuantity: 4,
    dispatchedQuantity: 120,
    installedQuantity: 96,
    unit: 'Panels',
    budgetedValue: 48500000,
    actualCostIncurred: 36900000,
    startDate: '2026-08-15',
    deadlineDate: '2026-10-20',
    forecastCompletionDate: '2026-10-18',
    priority: 'Critical Path',
    responsibleManager: 'Marcus Sterling',
    assignedEngineer: 'Eng. Nuwan Senanayake',
    executionInstructions: 'Maintain ±1.0mm diagonal tolerance on all unitized frames. Conduct 100% two-part silicone butterfly & snap-time tests every shift.',
    stageStatus: 'In Progress',
    completionPercent: 79,
    approvalMatrixTier: 'Tier 3 - QA + PM + Director',
    audit: {
      createdBy: 'Marcus Sterling',
      createdByRole: 'Project Manager',
      createdAt: '2026-08-10T09:00:00Z',
      updatedBy: 'Eng. Chaminda Rajapakse',
      updatedByRole: 'Plant Director',
      updatedAt: '2026-09-25T17:00:00Z',
      revision: 3,
      status: 'In Progress',
      approvalHistory: [
        { stage: 'Work Package Assignment', actorName: 'Marcus Sterling', actorRole: 'Project Manager', decision: 'Approved', timestamp: '2026-08-12T11:00:00Z', remarks: 'Released for shop-floor execution.' }
      ]
    }
  },
  {
    id: 'fwp-02',
    packageCode: 'FWP-2026-002',
    projectId: 'Apex Tower Structural Glazing',
    factoryId: 'fac-inv-02',
    projectName: 'Apex Tower Structural Glazing',
    factoryName: 'Innovista Heavy Structural Steel & Welding Workshop (Peliyagoda)',
    ownershipType: 'Innovista Owned',
    title: 'Hot-Dip Galvanized Steel Embedment Brackets & Atrium Spider Trusses',
    scopeDescription: 'Fabrication, AWS D1.1 full-penetration welding, UT NDT inspection, and epoxy blasting/priming of 240 heavy curtain wall anchor brackets and 16 atrium trusses.',
    boqReferenceCodes: ['BOQ-STL-204', 'BOQ-STL-209'],
    drawingNumbers: ['DRW-APX-STL-04 Rev D'],
    specificationCodes: ['SPEC-STL-S355JR', 'SPEC-WLD-AWSD1.1'],
    methodStatementCode: 'MOS-STL-WLD-04',
    itpPlanCode: 'ITP-STL-2026-04',
    plannedQuantity: 256,
    completedQuantity: 210,
    rejectedQuantity: 4,
    reworkQuantity: 6,
    dispatchedQuantity: 190,
    installedQuantity: 165,
    unit: 'Assemblies',
    budgetedValue: 32400000,
    actualCostIncurred: 26800000,
    startDate: '2026-08-20',
    deadlineDate: '2026-10-15',
    forecastCompletionDate: '2026-10-14',
    priority: 'High',
    responsibleManager: 'Marcus Sterling',
    assignedEngineer: 'Eng. Janaka Perera',
    executionInstructions: '100% Ultrasonic NDT testing required on primary tension welds prior to shot-blasting.',
    stageStatus: 'Submitted for Inspection',
    completionPercent: 82,
    approvalMatrixTier: 'Tier 2 - Factory & Project Manager',
    audit: {
      createdBy: 'Marcus Sterling',
      createdByRole: 'Project Manager',
      createdAt: '2026-08-18T10:00:00Z',
      updatedBy: 'Eng. Janaka Perera',
      updatedByRole: 'Workshop Manager',
      updatedAt: '2026-09-26T06:00:00Z',
      revision: 2,
      status: 'Submitted for Inspection',
      approvalHistory: [
        { stage: 'Batch 4 Submitted for UT Inspection', actorName: 'Eng. Janaka Perera', actorRole: 'Workshop Manager', decision: 'Submitted', timestamp: '2026-09-26T06:00:00Z', remarks: 'Ready for QA Lead David Okafor.' }
      ]
    }
  },
  {
    id: 'fwp-03',
    packageCode: 'FWP-2026-003',
    projectId: 'Emerald Pavilion Louvre & Canopy',
    projectName: 'Emerald Pavilion Louvre & Canopy',
    factoryId: 'fac-ext-03',
    factoryName: 'Alumex & Qualicoat Architectural Coating Partner Plant (Sapugaskanda)',
    ownershipType: 'Strategic Partner',
    title: 'PVDF 3-Coat Champagne Gold Aerofoil Louvres & Fire-Rated ACP Cassettes',
    scopeDescription: 'Surface pre-treatment, PVDF 3-coat fluorocarbon coating (min 40µm DFT), CNC V-grooving, and cassette assembly of 320 architectural sunshade louvres and ACP cladding panels.',
    boqReferenceCodes: ['BOQ-ACP-301', 'BOQ-LVR-305'],
    drawingNumbers: ['DRW-EMR-ACP-11 Rev B'],
    specificationCodes: ['SPEC-COAT-QUALICOAT2', 'SPEC-ACP-A2FR'],
    methodStatementCode: 'MOS-COAT-PVDF-02',
    itpPlanCode: 'ITP-COAT-2026-02',
    plannedQuantity: 320,
    completedQuantity: 280,
    rejectedQuantity: 2,
    reworkQuantity: 5,
    dispatchedQuantity: 240,
    installedQuantity: 180,
    unit: 'Cassettes',
    budgetedValue: 24600000,
    actualCostIncurred: 21100000,
    startDate: '2026-09-01',
    deadlineDate: '2026-10-25',
    forecastCompletionDate: '2026-10-22',
    priority: 'High',
    responsibleManager: 'Marcus Sterling',
    assignedEngineer: 'Sanjeewa Dias',
    executionInstructions: 'Record Elcometer DFT micron readings on every 10th cassette. Protective peel-off film must carry directional installation arrows.',
    stageStatus: 'Approved',
    completionPercent: 88,
    approvalMatrixTier: 'Tier 2 - Factory & Project Manager',
    audit: {
      createdBy: 'Marcus Sterling',
      createdByRole: 'Project Manager',
      createdAt: '2026-08-29T14:00:00Z',
      updatedBy: 'David Okafor',
      updatedByRole: 'Quality Inspector',
      updatedAt: '2026-09-25T15:10:00Z',
      revision: 2,
      status: 'Approved',
      approvalHistory: [
        { stage: 'QA Lot 3 Coating Inspection', actorName: 'David Okafor', actorRole: 'Quality Inspector', decision: 'Approved', timestamp: '2026-09-25T15:10:00Z', remarks: 'Mean DFT 43.2µm verified, cross-hatch 0B pass.' }
      ]
    }
  },
  {
    id: 'fwp-04',
    packageCode: 'FWP-2026-004',
    projectId: 'Sirius Mall Storefront',
    projectName: 'Sirius Mall High-Rise Curtain Wall',
    factoryId: 'fac-ext-04',
    factoryName: 'Guardian & EuroGlass Tempering & DGU Subcontractor Plant (Horana)',
    ownershipType: 'External Fabricator',
    title: '28mm Double Glazed Low-E Argon Filled Curtain Wall Vision Units',
    scopeDescription: 'CNC glass cutting, edge deletion of Low-E coating, horizontal convection tempering, heat-soak testing, and automated Argon DGU sealing.',
    boqReferenceCodes: ['BOQ-GLS-108'],
    drawingNumbers: ['DRW-SM-GLS-08 Rev C'],
    specificationCodes: ['SPEC-EN12150', 'SPEC-EN1279'],
    methodStatementCode: 'MOS-GLS-DGU-03',
    itpPlanCode: 'ITP-GLS-2026-03',
    plannedQuantity: 360,
    completedQuantity: 310,
    rejectedQuantity: 6,
    reworkQuantity: 6,
    dispatchedQuantity: 290,
    installedQuantity: 210,
    unit: 'DGU Panels',
    budgetedValue: 38900000,
    actualCostIncurred: 33200000,
    startDate: '2026-08-18',
    deadlineDate: '2026-10-12',
    forecastCompletionDate: '2026-10-11',
    priority: 'Critical Path',
    responsibleManager: 'Marcus Sterling',
    assignedEngineer: 'Vikramjit Singh',
    executionInstructions: 'Deliver directly to Innovista Biyagama Plant Glazing Bay 03 on returnable steel A-frames with batch fragmentation test certificates.',
    stageStatus: 'Dispatched',
    completionPercent: 86,
    approvalMatrixTier: 'Tier 3 - QA + PM + Director',
    audit: {
      createdBy: 'Marcus Sterling',
      createdByRole: 'Project Manager',
      createdAt: '2026-08-16T08:00:00Z',
      updatedBy: 'Vikramjit Singh',
      updatedByRole: 'Plant General Manager',
      updatedAt: '2026-09-25T18:00:00Z',
      revision: 3,
      status: 'Dispatched',
      approvalHistory: [
        { stage: 'FAT & Dispatch Release', actorName: 'Marcus Silva', actorRole: 'QA Lead', decision: 'Approved', timestamp: '2026-09-25T12:00:00Z', remarks: 'Optical distortion & Argon fill >92% verified.' }
      ]
    }
  }
];
