import { 
  Department, 
  Designation, 
  Role, 
  Permission, 
  SecurityUser, 
  UserSession, 
  SegregationOfDutyRule, 
  AccessRequest, 
  PermissionDelegation, 
  SecurityAuditEvent 
} from '../types/security';

export const SEED_DEPARTMENTS: Department[] = [
  {
    id: 'dept-ops',
    code: 'OPERATIONS',
    name: 'Operations & Execution',
    description: 'Core project planning, engineering fabrication, site construction, quality control and delivery.',
    color: 'orange',
    subDepartments: [
      'Project Management',
      'Project Planning',
      'Project Execution',
      'Quality Management',
      'Products & Fabrication',
      'Resource Allocation',
      'Resource Management',
      'Engineering',
      'Site Management',
      'Documentation',
      'Project Reporting'
    ],
    defaultTemplateId: 'tpl-ops-mgr',
    isActive: true
  },
  {
    id: 'dept-comm',
    code: 'COMMERCIAL_ADMIN',
    name: 'Commercial, HR & Administration',
    description: 'Financial controllership, corporate accounting, human resources, governance and executive reporting.',
    color: 'blue',
    subDepartments: [
      'Finance',
      'HR',
      'Payroll',
      'Administration',
      'Accounting',
      'Company Management',
      'Management Reporting'
    ],
    defaultTemplateId: 'tpl-fin-mgr',
    isActive: true
  },
  {
    id: 'dept-proc',
    code: 'PROCUREMENT_SUPPLY_CHAIN',
    name: 'Procurement & Supply Chain',
    description: 'Strategic sourcing, RFQ tendering, purchase orders, material inbound GRN, and supplier qualification.',
    color: 'emerald',
    subDepartments: [
      'Supplier Management',
      'RFQ & Tendering',
      'Purchasing',
      'Purchase Orders',
      'Goods Received (GRN)',
      'Supplier Evaluation',
      'Procurement Analytics'
    ],
    defaultTemplateId: 'tpl-store-off',
    isActive: true
  },
  {
    id: 'dept-fac',
    code: 'FACTORY_PRODUCTION',
    name: 'Factory, Workshop & Production',
    description: 'Internal and external fabrication plants, CNC machining, powder coating, assembly bays, and worksheets.',
    color: 'indigo',
    subDepartments: [
      'Curtain Wall Bay',
      'Structural Steel Workshop',
      'CNC & Cutting Lines',
      'Glazing & Silicone Bay',
      'Powder Coating Line',
      'Packing & Crating'
    ],
    defaultTemplateId: 'tpl-fac-mgr',
    isActive: true
  },
  {
    id: 'dept-qc',
    code: 'QUALITY',
    name: 'Quality Assurance & Lab (QA/QC)',
    description: 'ITP Hold Points, Mill Test Certificates, FAI/FAT inspections, NCR quarantine, and ISO 17025 calibration.',
    color: 'teal',
    subDepartments: [
      'Incoming Material QC',
      'In-Process Fabrication QC',
      'FAT & CWCT Hose Testing',
      'NCR & CAPA Governance'
    ],
    defaultTemplateId: 'tpl-qa-qc',
    isActive: true
  },
  {
    id: 'dept-hse',
    code: 'HSE',
    name: 'Health, Safety & Environment (HSE)',
    description: 'Permit-to-Work (PTW) authorizations, Job Safety Analysis, toolbox talks, and incident investigations.',
    color: 'amber',
    subDepartments: [
      'Factory Safety',
      'Tower Erection Safety',
      'PTW & Lifting Rigging',
      'Environmental Compliance'
    ],
    defaultTemplateId: 'tpl-hse-off',
    isActive: true
  },
  {
    id: 'dept-eng',
    code: 'ENGINEERING',
    name: 'Engineering, Design & QS',
    description: 'Facade structural engineering, AFC shop drawings, multi-level BOMs, cutting lists, and BOQ estimation.',
    color: 'violet',
    subDepartments: [
      'Facade Design & BIM',
      'Structural Calculation',
      'Quantity Surveying (QS)',
      'CNC CAM Programming'
    ],
    defaultTemplateId: 'tpl-proj-eng',
    isActive: true
  },
  {
    id: 'dept-log',
    code: 'LOGISTICS',
    name: 'Logistics, Fleet & Dispatch',
    description: 'Stillage crating, gate pass verification, heavy fleet transport, and site receiving verification.',
    color: 'cyan',
    subDepartments: [
      'Dispatch & Gate Control',
      'Heavy Fleet Operations',
      'Site Crane Receiving'
    ],
    defaultTemplateId: 'tpl-log-mgr',
    isActive: true
  }
];

export const SEED_DESIGNATIONS: Designation[] = [
  { id: 'des-01', title: 'Managing Director & Chief Engineer', departmentCode: 'COMMERCIAL_ADMIN', level: 'Executive' },
  { id: 'des-02', title: 'Operations Director', departmentCode: 'OPERATIONS', level: 'Executive' },
  { id: 'des-03', title: 'Head of Quality Assurance', departmentCode: 'QUALITY', level: 'Management' },
  { id: 'des-04', title: 'Senior Project Manager', departmentCode: 'OPERATIONS', level: 'Senior' },
  { id: 'des-05', title: 'Lead Structural & Facade Engineer', departmentCode: 'ENGINEERING', level: 'Senior' },
  { id: 'des-06', title: 'Chief Quantity Surveyor', departmentCode: 'ENGINEERING', level: 'Senior' },
  { id: 'des-07', title: 'Site Construction Manager', departmentCode: 'OPERATIONS', level: 'Management' },
  { id: 'des-08', title: 'Senior QA/QC Inspector', departmentCode: 'QUALITY', level: 'Operational' },
  { id: 'des-09', title: 'Financial Controller', departmentCode: 'COMMERCIAL_ADMIN', level: 'Management' },
  { id: 'des-10', title: 'Senior Corporate Accountant', departmentCode: 'COMMERCIAL_ADMIN', level: 'Senior' },
  { id: 'des-11', title: 'Human Resources Director', departmentCode: 'COMMERCIAL_ADMIN', level: 'Management' },
  { id: 'des-12', title: 'Procurement Director', departmentCode: 'PROCUREMENT_SUPPLY_CHAIN', level: 'Management' },
  { id: 'des-13', title: 'Senior Sourcing Officer', departmentCode: 'PROCUREMENT_SUPPLY_CHAIN', level: 'Operational' },
  { id: 'des-14', title: 'Principal System Administrator', departmentCode: 'COMMERCIAL_ADMIN', level: 'Senior' },
  { id: 'des-15', title: 'Plant & Factory Manager', departmentCode: 'FACTORY_PRODUCTION', level: 'Management' },
  { id: 'des-16', title: 'Workshop & Bay Supervisor', departmentCode: 'FACTORY_PRODUCTION', level: 'Operational' },
  { id: 'des-17', title: 'Lead CNC & Fabrication Technician', departmentCode: 'FACTORY_PRODUCTION', level: 'Operational' },
  { id: 'des-18', title: 'Principal HSE Officer', departmentCode: 'HSE', level: 'Senior' },
  { id: 'des-19', title: 'External Partner Plant Director', departmentCode: 'FACTORY_PRODUCTION', level: 'Management' },
  { id: 'des-20', title: 'Client Executive Representative', departmentCode: 'COMMERCIAL_ADMIN', level: 'Executive' }
];

// Generate granular permissions across 25 modules and 27 actions
const MODULE_DEPT_MAPPINGS = [
  { module: 'Project Management', prefix: 'project', dept: 'OPERATIONS' },
  { module: 'Project Planning & Gantt', prefix: 'planning', dept: 'OPERATIONS' },
  { module: 'Factory & Site Execution', prefix: 'execution', dept: 'FACTORY_PRODUCTION' },
  { module: 'Quality Control & Inspections', prefix: 'qc', dept: 'QUALITY' },
  { module: 'Products & BOQ Master', prefix: 'boq', dept: 'ENGINEERING' },
  { module: 'Resource & Labour Allocation', prefix: 'resource', dept: 'OPERATIONS' },
  { module: 'Equipment & Machinery', prefix: 'equipment', dept: 'FACTORY_PRODUCTION' },
  { module: 'Site Management & HSE Permits', prefix: 'site', dept: 'HSE' },
  { module: 'Engineering Specifications', prefix: 'engineering', dept: 'ENGINEERING' },
  { module: 'Operational Documentation', prefix: 'doc', dept: 'OPERATIONS' },
  { module: 'Project Reporting', prefix: 'proj_report', dept: 'OPERATIONS' },
  { module: 'Finance & Invoicing', prefix: 'invoice', dept: 'COMMERCIAL_ADMIN' },
  { module: 'Corporate Accounting', prefix: 'accounting', dept: 'COMMERCIAL_ADMIN' },
  { module: 'HR & Personnel', prefix: 'hr', dept: 'COMMERCIAL_ADMIN' },
  { module: 'Payroll Management', prefix: 'payroll', dept: 'COMMERCIAL_ADMIN' },
  { module: 'Company Management', prefix: 'company', dept: 'COMMERCIAL_ADMIN' },
  { module: 'Executive Reporting', prefix: 'mgmt_report', dept: 'COMMERCIAL_ADMIN' },
  { module: 'Supplier Directory', prefix: 'supplier', dept: 'PROCUREMENT_SUPPLY_CHAIN' },
  { module: 'RFQ & Tenders', prefix: 'rfq', dept: 'PROCUREMENT_SUPPLY_CHAIN' },
  { module: 'Purchase Orders', prefix: 'po', dept: 'PROCUREMENT_SUPPLY_CHAIN' },
  { module: 'Goods Received (GRN)', prefix: 'grn', dept: 'PROCUREMENT_SUPPLY_CHAIN' },
  { module: 'Supplier Evaluation', prefix: 'supplier_eval', dept: 'PROCUREMENT_SUPPLY_CHAIN' },
  { module: 'Procurement Analytics', prefix: 'proc_analytics', dept: 'PROCUREMENT_SUPPLY_CHAIN' },
  { module: 'User & Access Security', prefix: 'security', dept: 'SYSTEM' },
  { module: 'Audit & Compliance', prefix: 'audit', dept: 'SYSTEM' }
];

const STANDARD_ACTIONS = [
  { action: 'view', risk: 'Low', dual: false },
  { action: 'create', risk: 'Medium', dual: false },
  { action: 'edit', risk: 'Medium', dual: false },
  { action: 'delete', risk: 'High', dual: true },
  { action: 'archive', risk: 'High', dual: false },
  { action: 'restore', risk: 'High', dual: false },
  { action: 'approve', risk: 'High', dual: true },
  { action: 'reject', risk: 'Medium', dual: false },
  { action: 'submit', risk: 'Low', dual: false },
  { action: 'assign', risk: 'Medium', dual: false },
  { action: 'reassign', risk: 'Medium', dual: false },
  { action: 'transfer', risk: 'Medium', dual: false },
  { action: 'import', risk: 'Medium', dual: false },
  { action: 'export', risk: 'High', dual: false },
  { action: 'download', risk: 'Medium', dual: false },
  { action: 'upload', risk: 'Low', dual: false },
  { action: 'print', risk: 'Low', dual: false },
  { action: 'share', risk: 'Medium', dual: false },
  { action: 'comment', risk: 'Low', dual: false },
  { action: 'execute', risk: 'Medium', dual: false },
  { action: 'close', risk: 'Medium', dual: false },
  { action: 'reopen', risk: 'High', dual: false },
  { action: 'lock', risk: 'High', dual: false },
  { action: 'unlock', risk: 'Critical', dual: true },
  { action: 'manage', risk: 'High', dual: false },
  { action: 'configure', risk: 'High', dual: true },
  { action: 'admin', risk: 'Critical', dual: true }
] as const;

export const SEED_PERMISSIONS: Permission[] = MODULE_DEPT_MAPPINGS.flatMap((m) => 
  STANDARD_ACTIONS.map((a) => ({
    id: `perm-${m.prefix}-${a.action}`,
    code: `${m.prefix}.${a.action}`,
    module: m.module,
    departmentCode: m.dept as any,
    action: a.action,
    name: `${a.action.charAt(0).toUpperCase() + a.action.slice(1)} ${m.module}`,
    description: `Grants capability to ${a.action} records in ${m.module}.`,
    riskLevel: a.risk,
    requiresDualApproval: a.dual
  }))
);

const ALL_PERMISSION_CODES = SEED_PERMISSIONS.map(p => p.code);

export const SEED_ROLES: Role[] = [
  {
    id: 'role-superadmin',
    name: 'Super Administrator',
    code: 'SUPER_ADMIN',
    userTypeCode: 'SUPER_ADMIN',
    adminAuthorityLevel: 'SUPER_ADMINISTRATOR',
    isSystem: true,
    description: 'Supreme unconstrained authority over all organizations, branches, portals, security policies, data scopes, and audit trails.',
    defaultScope: 'Global',
    authorizedPortalIds: [
      'company-control-center',
      'executive-dashboard',
      'project-management',
      'construction-site-management',
      'factory-workshop-management',
      'production-control',
      'quality-assurance',
      'hse-safety',
      'human-resources',
      'accounting-finance',
      'inventory-warehouse',
      'procurement-supply-chain',
      'logistics-dispatch',
      'equipment-machinery',
      'document-control',
      'customer-portal',
      'supplier-portal',
      'partner-factory-portal',
      'reporting-analytics',
      'engineering-qs-boq',
      'sales-crm-quotes',
      'system-administration'
    ],
    permissionCodes: [...ALL_PERMISSION_CODES],
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z'
  },
  {
    id: 'role-sysadmin',
    name: 'System Administrator',
    code: 'SYSTEM_ADMIN',
    departmentCode: 'COMMERCIAL_ADMIN',
    userTypeCode: 'SYSTEM_ADMINISTRATOR',
    adminAuthorityLevel: 'SYSTEM_ADMINISTRATOR',
    isSystem: true,
    description: 'Manages user accounts, authentication policies, role permissions, portal access, API clients, and security diagnostics.',
    defaultScope: 'Global',
    authorizedPortalIds: [
      'company-control-center',
      'system-administration',
      'document-control',
      'executive-dashboard'
    ],
    permissionCodes: ALL_PERMISSION_CODES.filter(c => c.startsWith('security.') || c.startsWith('audit.') || c.startsWith('company.') || c === 'doc.view' || c === 'mgmt_report.view'),
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z'
  },
  {
    id: 'role-deptadmin',
    name: 'Department Administrator',
    code: 'DEPT_ADMIN',
    departmentCode: 'OPERATIONS',
    userTypeCode: 'MANAGEMENT',
    adminAuthorityLevel: 'DEPARTMENT_ADMINISTRATOR',
    isSystem: false,
    description: 'Administrative control over users, workflows, and configurations within an assigned department.',
    defaultScope: 'Department',
    authorizedPortalIds: [
      'company-control-center',
      'executive-dashboard',
      'project-management',
      'construction-site-management',
      'factory-workshop-management',
      'quality-assurance',
      'hse-safety',
      'reporting-analytics'
    ],
    permissionCodes: ALL_PERMISSION_CODES.filter(c => c.startsWith('project.') || c.startsWith('planning.') || c.startsWith('execution.') || c.startsWith('qc.') || c.startsWith('resource.') || c.startsWith('site.') || c === 'proj_report.view'),
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z'
  },
  {
    id: 'role-md',
    name: 'Managing Director / Executive',
    code: 'MANAGING_DIRECTOR',
    departmentCode: 'COMMERCIAL_ADMIN',
    userTypeCode: 'EXECUTIVE',
    adminAuthorityLevel: 'DEPARTMENT_ADMINISTRATOR',
    isSystem: true,
    description: 'Executive oversight, company-wide reporting, strategic financial sign-offs, and critical approvals.',
    defaultScope: 'Global',
    authorizedPortalIds: [
      'company-control-center',
      'executive-dashboard',
      'project-management',
      'accounting-finance',
      'reporting-analytics',
      'factory-workshop-management',
      'procurement-supply-chain',
      'human-resources',
      'sales-crm-quotes'
    ],
    permissionCodes: ALL_PERMISSION_CODES.filter(c => c.includes('.view') || c.includes('.approve') || c.includes('.export') || c.startsWith('mgmt_report.') || c.startsWith('proj_report.')),
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z'
  },
  {
    id: 'role-opsmanager',
    name: 'Operations Manager',
    code: 'OPERATIONS_MANAGER',
    departmentCode: 'OPERATIONS',
    userTypeCode: 'OPERATIONS_MANAGER',
    adminAuthorityLevel: 'PORTAL_ADMINISTRATOR',
    isSystem: false,
    description: 'Full supervisory authority over all Operations projects, multi-factory allocations, fabrication schedules, and QA handovers.',
    defaultScope: 'Department',
    authorizedPortalIds: [
      'company-control-center',
      'executive-dashboard',
      'project-management',
      'construction-site-management',
      'factory-workshop-management',
      'production-control',
      'quality-assurance',
      'hse-safety',
      'equipment-machinery',
      'logistics-dispatch',
      'document-control'
    ],
    permissionCodes: ALL_PERMISSION_CODES.filter(c => c.startsWith('project.') || c.startsWith('planning.') || c.startsWith('execution.') || c.startsWith('qc.') || c.startsWith('boq.') || c.startsWith('resource.') || c.startsWith('equipment.') || c.startsWith('site.') || c.startsWith('engineering.') || c.startsWith('doc.') || c.startsWith('proj_report.')),
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z'
  },
  {
    id: 'role-pm',
    name: 'Project Manager',
    code: 'PROJECT_MANAGER',
    departmentCode: 'OPERATIONS',
    userTypeCode: 'PROJECT_MANAGER',
    adminAuthorityLevel: 'PROJECT_ADMINISTRATOR',
    isSystem: false,
    description: 'End-to-end execution, milestone tracking, BOQ variation approvals, factory work package assignment, and team governance on assigned projects.',
    defaultScope: 'Project',
    authorizedPortalIds: [
      'company-control-center',
      'project-management',
      'construction-site-management',
      'factory-workshop-management',
      'quality-assurance',
      'hse-safety',
      'document-control',
      'reporting-analytics'
    ],
    permissionCodes: [
      'project.view', 'project.create', 'project.edit', 'project.submit', 'project.approve', 'project.assign', 'project.reassign', 'project.export', 'project.lock', 'project.close',
      'planning.view', 'planning.create', 'planning.edit', 'planning.submit', 'planning.approve', 'planning.export',
      'execution.view', 'execution.create', 'execution.edit', 'execution.submit', 'execution.approve', 'execution.assign', 'execution.upload', 'execution.print',
      'boq.view', 'boq.create', 'boq.edit', 'boq.submit', 'boq.export', 'boq.lock',
      'resource.view', 'resource.assign', 'resource.export',
      'qc.view', 'qc.create', 'qc.export',
      'site.view', 'site.create', 'site.export',
      'doc.view', 'doc.upload', 'doc.download', 'doc.print', 'doc.share',
      'proj_report.view', 'proj_report.export'
    ],
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z'
  },
  {
    id: 'role-facmgr',
    name: 'Factory Manager',
    code: 'FACTORY_MANAGER',
    departmentCode: 'FACTORY_PRODUCTION',
    userTypeCode: 'FACTORY_MANAGER',
    adminAuthorityLevel: 'FACTORY_ADMINISTRATOR',
    isSystem: false,
    description: 'Full operational command over assigned internal fabrication plants, production bays, work packages, worksheets, machinery, and dispatch.',
    defaultScope: 'Factory',
    authorizedPortalIds: [
      'company-control-center',
      'factory-workshop-management',
      'production-control',
      'quality-assurance',
      'hse-safety',
      'inventory-warehouse',
      'equipment-machinery',
      'logistics-dispatch',
      'document-control'
    ],
    permissionCodes: [
      'project.view', 'planning.view',
      'execution.view', 'execution.create', 'execution.edit', 'execution.submit', 'execution.approve', 'execution.reject', 'execution.assign', 'execution.reassign', 'execution.upload', 'execution.download', 'execution.print', 'execution.execute', 'execution.close',
      'engineering.view', 'engineering.create', 'engineering.edit', 'engineering.print', 'boq.view',
      'qc.view', 'qc.create', 'qc.edit', 'qc.submit', 'qc.upload', 'qc.print',
      'site.view', 'site.create', 'site.edit', 'site.approve',
      'resource.view', 'resource.create', 'resource.edit', 'resource.assign',
      'equipment.view', 'equipment.create', 'equipment.edit', 'equipment.assign',
      'grn.view', 'grn.create',
      'doc.view', 'doc.upload', 'doc.download', 'doc.print', 'proj_report.view'
    ],
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z'
  },
  {
    id: 'role-workshopmgr',
    name: 'Workshop Manager',
    code: 'WORKSHOP_MANAGER',
    departmentCode: 'FACTORY_PRODUCTION',
    userTypeCode: 'WORKSHOP_MANAGER',
    adminAuthorityLevel: 'STANDARD_USER',
    isSystem: false,
    description: 'Supervises specialized workshop bays (Curtain Wall, Steel, Powder Coating), job cards, daily logs, and tool maintenance.',
    defaultScope: 'Workshop',
    authorizedPortalIds: [
      'company-control-center',
      'factory-workshop-management',
      'production-control',
      'quality-assurance',
      'equipment-machinery',
      'document-control'
    ],
    permissionCodes: [
      'project.view', 'execution.view', 'execution.create', 'execution.edit', 'execution.submit', 'execution.assign', 'execution.upload', 'execution.print', 'execution.execute',
      'engineering.view', 'engineering.print', 'qc.view', 'qc.create', 'site.view', 'site.create', 'resource.view', 'equipment.view', 'doc.view', 'doc.download'
    ],
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z'
  },
  {
    id: 'role-fabricator',
    name: 'Shop-Floor Fabricator & CNC Operator',
    code: 'FABRICATOR',
    departmentCode: 'FACTORY_PRODUCTION',
    userTypeCode: 'FABRICATOR',
    adminAuthorityLevel: 'STANDARD_USER',
    isSystem: false,
    description: 'Executes assigned fabrication tasks, updates stage gates, records digital worksheets, and uploads photo/video completion evidence.',
    defaultScope: 'Assigned Records',
    authorizedPortalIds: [
      'company-control-center',
      'factory-workshop-management',
      'document-control'
    ],
    permissionCodes: [
      'project.view', 'execution.view', 'execution.edit', 'execution.submit', 'execution.upload', 'execution.execute', 'execution.print',
      'engineering.view', 'engineering.print', 'qc.view', 'qc.create', 'equipment.view', 'doc.view', 'doc.download'
    ],
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z'
  },
  {
    id: 'role-pcoord',
    name: 'Project Coordinator',
    code: 'PROJECT_COORDINATOR',
    departmentCode: 'OPERATIONS',
    userTypeCode: 'PROJECT_ENGINEER',
    isSystem: false,
    description: 'Supports project delivery, schedule updates, meeting notes, document verification and site liaisons.',
    defaultScope: 'Project',
    authorizedPortalIds: [
      'company-control-center',
      'project-management',
      'construction-site-management',
      'document-control'
    ],
    permissionCodes: [
      'project.view', 'planning.view', 'planning.edit', 'execution.view', 'boq.view',
      'resource.view', 'qc.view', 'site.view', 'doc.view', 'doc.upload', 'doc.download'
    ],
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z'
  },
  {
    id: 'role-sitemgr',
    name: 'Site Manager',
    code: 'SITE_MANAGER',
    departmentCode: 'OPERATIONS',
    userTypeCode: 'SITE_SUPERVISOR',
    isSystem: false,
    description: 'On-site construction oversight, labor supervision, safety permits, plant logistics and daily site logs.',
    defaultScope: 'Branch',
    authorizedPortalIds: [
      'company-control-center',
      'construction-site-management',
      'hse-safety',
      'quality-assurance',
      'equipment-machinery',
      'logistics-dispatch',
      'document-control'
    ],
    permissionCodes: [
      'project.view', 'site.view', 'site.create', 'site.edit', 'site.approve', 'site.export',
      'execution.view', 'execution.edit', 'execution.submit', 'execution.upload',
      'equipment.view', 'equipment.assign', 'resource.view', 'qc.view', 'qc.create', 'doc.view', 'doc.upload'
    ],
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z'
  },
  {
    id: 'role-sitesup',
    name: 'Site Supervisor',
    code: 'SITE_SUPERVISOR',
    departmentCode: 'OPERATIONS',
    userTypeCode: 'SITE_SUPERVISOR',
    isSystem: false,
    description: 'Direct field crew supervision, work permit checks, material staging and daily site log entries.',
    defaultScope: 'Project',
    authorizedPortalIds: [
      'company-control-center',
      'construction-site-management',
      'hse-safety',
      'quality-assurance',
      'document-control'
    ],
    permissionCodes: [
      'project.view', 'site.view', 'site.create', 'site.edit', 'site.submit', 'site.upload',
      'execution.view', 'execution.edit', 'equipment.view', 'resource.view', 'qc.view', 'qc.create', 'doc.view'
    ],
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z'
  },
  {
    id: 'role-hse',
    name: 'HSE Safety Officer',
    code: 'HSE_OFFICER',
    departmentCode: 'HSE',
    userTypeCode: 'HSE_OFFICER',
    isSystem: false,
    description: 'Authorizes Permit-to-Work (PTW), inspects harnesses and scaffolds, leads toolbox talks, and investigates incidents.',
    defaultScope: 'Branch',
    authorizedPortalIds: [
      'company-control-center',
      'hse-safety',
      'construction-site-management',
      'factory-workshop-management',
      'document-control'
    ],
    permissionCodes: [
      'project.view', 'site.view', 'site.create', 'site.edit', 'site.approve', 'site.reject', 'site.close', 'site.print', 'site.upload',
      'execution.view', 'equipment.view', 'doc.view', 'doc.upload'
    ],
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z'
  },
  {
    id: 'role-engineer',
    name: 'Project & Facade Engineer',
    code: 'ENGINEER',
    departmentCode: 'ENGINEERING',
    userTypeCode: 'PROJECT_ENGINEER',
    isSystem: false,
    description: 'Structural calculation review, AFC fabrication drawings, multi-level BOMs, cutting lists, and technical submittals.',
    defaultScope: 'Project',
    authorizedPortalIds: [
      'company-control-center',
      'project-management',
      'production-control',
      'engineering-qs-boq',
      'quality-assurance',
      'document-control'
    ],
    permissionCodes: [
      'project.view', 'engineering.view', 'engineering.create', 'engineering.edit', 'engineering.submit', 'engineering.approve', 'engineering.export', 'engineering.print',
      'execution.view', 'execution.create', 'execution.edit', 'boq.view', 'qc.view', 'qc.create', 'doc.view', 'doc.upload', 'doc.download', 'doc.print'
    ],
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z'
  },
  {
    id: 'role-qs',
    name: 'QS (Quantity Surveyor)',
    code: 'QUANTITY_SURVEYOR',
    departmentCode: 'ENGINEERING',
    userTypeCode: 'QS',
    isSystem: false,
    description: 'Bill of Quantities formulation, material takeoff precision, rate analyses, variation claims, and IPC valuations.',
    defaultScope: 'Department',
    authorizedPortalIds: [
      'company-control-center',
      'engineering-qs-boq',
      'sales-crm-quotes',
      'project-management',
      'reporting-analytics',
      'document-control'
    ],
    permissionCodes: [
      'project.view', 'boq.view', 'boq.create', 'boq.edit', 'boq.submit', 'boq.export', 'boq.lock', 'boq.print',
      'invoice.view', 'invoice.create', 'invoice.submit', 'doc.view', 'doc.download', 'doc.upload', 'proj_report.view'
    ],
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z'
  },
  {
    id: 'role-qcmgr',
    name: 'Quality Manager (QA/QC)',
    code: 'QUALITY_MANAGER',
    departmentCode: 'QUALITY',
    userTypeCode: 'QA_QC_OFFICER',
    isSystem: false,
    description: 'Quality assurance protocol sign-off, non-conformance closure, inspection test plans, FAT release, and warranty certificates.',
    defaultScope: 'Department',
    authorizedPortalIds: [
      'company-control-center',
      'quality-assurance',
      'factory-workshop-management',
      'construction-site-management',
      'document-control'
    ],
    permissionCodes: [
      'project.view', 'execution.view', 'qc.view', 'qc.create', 'qc.edit', 'qc.approve', 'qc.reject', 'qc.close', 'qc.reopen', 'qc.export', 'qc.lock', 'qc.upload', 'qc.print',
      'doc.view', 'doc.upload', 'doc.download', 'doc.print'
    ],
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z'
  },
  {
    id: 'role-qcinspec',
    name: 'Quality Inspector',
    code: 'QUALITY_INSPECTOR',
    departmentCode: 'QUALITY',
    userTypeCode: 'QA_QC_OFFICER',
    isSystem: false,
    description: 'Shop fabrication and on-site tolerance measurements, weld inspection reports, and initial NCR filings.',
    defaultScope: 'Factory',
    authorizedPortalIds: [
      'company-control-center',
      'quality-assurance',
      'factory-workshop-management',
      'document-control'
    ],
    permissionCodes: [
      'project.view', 'execution.view', 'qc.view', 'qc.create', 'qc.edit', 'qc.submit', 'qc.approve', 'qc.reject', 'qc.export', 'qc.upload', 'qc.print', 'doc.view', 'doc.upload'
    ],
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z'
  },
  {
    id: 'role-resmgr',
    name: 'Store & Resource Manager',
    code: 'RESOURCE_MANAGER',
    departmentCode: 'OPERATIONS',
    userTypeCode: 'STORE_RESOURCE_OFFICER',
    isSystem: false,
    description: 'Warehouse inventory, GRN receiving, material issue slips, plant equipment dispatch, and skilled technician rosters.',
    defaultScope: 'Branch',
    authorizedPortalIds: [
      'company-control-center',
      'inventory-warehouse',
      'equipment-machinery',
      'factory-workshop-management',
      'logistics-dispatch'
    ],
    permissionCodes: [
      'project.view', 'execution.view', 'resource.view', 'resource.create', 'resource.edit', 'resource.approve', 'resource.assign', 'resource.export',
      'equipment.view', 'equipment.create', 'equipment.edit', 'equipment.assign', 'equipment.export',
      'grn.view', 'grn.create', 'grn.edit', 'grn.submit', 'grn.approve', 'po.view'
    ],
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z'
  },
  {
    id: 'role-finmgr',
    name: 'Finance Manager',
    code: 'FINANCE_MANAGER',
    departmentCode: 'COMMERCIAL_ADMIN',
    userTypeCode: 'FINANCE_MANAGER',
    isSystem: false,
    description: 'Commercial governance, invoice sign-off, retention releases, 3-way match PVC release, treasury management, and audit verification.',
    defaultScope: 'Department',
    authorizedPortalIds: [
      'company-control-center',
      'accounting-finance',
      'reporting-analytics',
      'executive-dashboard',
      'procurement-supply-chain'
    ],
    permissionCodes: [
      'invoice.view', 'invoice.create', 'invoice.edit', 'invoice.approve', 'invoice.reject', 'invoice.export', 'invoice.print',
      'accounting.view', 'accounting.create', 'accounting.edit', 'accounting.approve', 'accounting.export', 'accounting.lock',
      'payroll.view', 'payroll.approve', 'mgmt_report.view', 'mgmt_report.export', 'project.view', 'po.view', 'grn.view'
    ],
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z'
  },
  {
    id: 'role-acct',
    name: 'Accountant',
    code: 'ACCOUNTANT',
    departmentCode: 'COMMERCIAL_ADMIN',
    userTypeCode: 'FINANCE_ACCOUNTING_OFFICER',
    isSystem: false,
    description: 'Accounts payable/receivable booking, VAT filing, bank reconciliations, and payment voucher preparation.',
    defaultScope: 'Department',
    authorizedPortalIds: [
      'company-control-center',
      'accounting-finance',
      'reporting-analytics'
    ],
    permissionCodes: [
      'invoice.view', 'invoice.create', 'invoice.edit', 'invoice.submit', 'invoice.export',
      'accounting.view', 'accounting.create', 'accounting.edit', 'accounting.export', 'mgmt_report.view'
    ],
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z'
  },
  {
    id: 'role-hrmgr',
    name: 'HR Manager',
    code: 'HR_MANAGER',
    departmentCode: 'COMMERCIAL_ADMIN',
    userTypeCode: 'HR_MANAGER',
    isSystem: false,
    description: 'Talent recruitment, employment contracts, biometric attendance review, personnel compliance, and leave/payroll governance.',
    defaultScope: 'Department',
    authorizedPortalIds: [
      'company-control-center',
      'human-resources',
      'reporting-analytics'
    ],
    permissionCodes: [
      'hr.view', 'hr.create', 'hr.edit', 'hr.approve', 'hr.export', 'hr.admin', 'hr.archive',
      'payroll.view', 'payroll.create', 'payroll.edit', 'payroll.submit', 'payroll.export', 'doc.view', 'doc.upload'
    ],
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z'
  },
  {
    id: 'role-hrofficer',
    name: 'HR Officer',
    code: 'HR_OFFICER',
    departmentCode: 'COMMERCIAL_ADMIN',
    userTypeCode: 'HR_OFFICER',
    isSystem: false,
    description: 'Day-to-day employee documentation, visa tracking, shift attendance, and personnel record maintenance.',
    defaultScope: 'Department',
    authorizedPortalIds: [
      'company-control-center',
      'human-resources'
    ],
    permissionCodes: [
      'hr.view', 'hr.create', 'hr.edit', 'hr.submit', 'payroll.view', 'doc.view', 'doc.upload'
    ],
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z'
  },
  {
    id: 'role-procmgr',
    name: 'Procurement Manager',
    code: 'PROCUREMENT_MANAGER',
    departmentCode: 'PROCUREMENT_SUPPLY_CHAIN',
    userTypeCode: 'OPERATIONS_MANAGER',
    isSystem: false,
    description: 'Strategic sourcing approval, high-value purchase orders, supplier qualification, and supplier scorecards.',
    defaultScope: 'Department',
    authorizedPortalIds: [
      'company-control-center',
      'procurement-supply-chain',
      'inventory-warehouse',
      'reporting-analytics'
    ],
    permissionCodes: [
      'supplier.view', 'supplier.create', 'supplier.edit', 'supplier.approve', 'supplier.export',
      'rfq.view', 'rfq.create', 'rfq.edit', 'rfq.approve', 'rfq.export',
      'po.view', 'po.create', 'po.edit', 'po.approve', 'po.reject', 'po.export', 'po.print',
      'grn.view', 'supplier_eval.view', 'supplier_eval.create', 'supplier_eval.approve', 'proc_analytics.view', 'proc_analytics.export'
    ],
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z'
  },
  // EXTERNAL ECOSYSTEM ROLES
  {
    id: 'role-ext-fac-mgr',
    name: 'External Partner Factory Manager',
    code: 'EXTERNAL_FACTORY_MANAGER',
    departmentCode: 'FACTORY_PRODUCTION',
    userTypeCode: 'EXTERNAL_FACTORY_MANAGER',
    isSystem: false,
    isExternalRole: true,
    description: 'External partner plant manager restricted strictly to assigned factory work packages, approved drawings, worksheets, QC submissions, and dispatch packing lists.',
    defaultScope: 'Factory',
    authorizedPortalIds: [
      'company-control-center',
      'partner-factory-portal',
      'factory-workshop-management',
      'document-control'
    ],
    permissionCodes: [
      'project.view', 'execution.view', 'execution.edit', 'execution.submit', 'execution.upload', 'execution.download', 'execution.print', 'execution.execute',
      'qc.view', 'qc.create', 'qc.submit', 'qc.upload', 'doc.view', 'doc.download', 'doc.upload'
    ],
    deniedPermissionCodes: ['invoice.view', 'accounting.view', 'payroll.view', 'hr.view', 'security.view', 'boq.edit'],
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z'
  },
  {
    id: 'role-ext-fac-worker',
    name: 'External Partner Workshop Operator',
    code: 'EXTERNAL_FACTORY_WORKER',
    departmentCode: 'FACTORY_PRODUCTION',
    userTypeCode: 'EXTERNAL_FACTORY_WORKER',
    isSystem: false,
    isExternalRole: true,
    description: 'External shop-floor fabricator restricted to assigned job cards, worksheet completion, and photo upload within their partner factory.',
    defaultScope: 'Assigned Records',
    authorizedPortalIds: [
      'company-control-center',
      'partner-factory-portal',
      'factory-workshop-management'
    ],
    permissionCodes: [
      'execution.view', 'execution.edit', 'execution.submit', 'execution.upload', 'execution.execute', 'qc.view', 'doc.view', 'doc.download'
    ],
    deniedPermissionCodes: ['invoice.view', 'accounting.view', 'payroll.view', 'hr.view', 'security.view'],
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z'
  },
  {
    id: 'role-customer',
    name: 'Client / Customer Representative',
    code: 'CUSTOMER_PORTAL_USER',
    departmentCode: 'COMMERCIAL_ADMIN',
    userTypeCode: 'B2B_CLIENT',
    isSystem: false,
    isExternalRole: true,
    description: 'External customer organization user restricted to their own project progress, approved submittals, variation approvals, and billing statements.',
    defaultScope: 'Organization',
    authorizedPortalIds: [
      'company-control-center',
      'customer-portal',
      'document-control'
    ],
    permissionCodes: [
      'project.view', 'doc.view', 'doc.download', 'doc.approve', 'doc.reject', 'doc.comment', 'invoice.view', 'invoice.download', 'invoice.print'
    ],
    deniedPermissionCodes: ['accounting.view', 'payroll.view', 'hr.view', 'security.view', 'supplier.view', 'po.view'],
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z'
  },
  {
    id: 'role-supplier',
    name: 'External Supplier / Vendor Representative',
    code: 'SUPPLIER_PORTAL_USER',
    departmentCode: 'PROCUREMENT_SUPPLY_CHAIN',
    userTypeCode: 'SUPPLIER',
    isSystem: false,
    isExternalRole: true,
    description: 'External supplier user restricted to viewing invited RFQs, acknowledging purchase orders, uploading ASN/MTC certificates, and submitting invoices.',
    defaultScope: 'Organization',
    authorizedPortalIds: [
      'company-control-center',
      'supplier-portal'
    ],
    permissionCodes: [
      'rfq.view', 'rfq.submit', 'rfq.upload', 'po.view', 'po.download', 'grn.view', 'invoice.create', 'invoice.submit', 'doc.view', 'doc.upload'
    ],
    deniedPermissionCodes: ['project.edit', 'accounting.view', 'payroll.view', 'hr.view', 'security.view'],
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z'
  },
  {
    id: 'role-consultant',
    name: 'External Engineering Consultant / Engineer of Record',
    code: 'EXTERNAL_CONSULTANT',
    departmentCode: 'ENGINEERING',
    userTypeCode: 'CONSULTANT',
    isSystem: false,
    isExternalRole: true,
    description: 'External facade/structural consultant authorized to review and approve AFC drawings, ITP hold points, and WIR site inspections on assigned projects.',
    defaultScope: 'Project',
    authorizedPortalIds: [
      'company-control-center',
      'document-control',
      'quality-assurance',
      'project-management'
    ],
    permissionCodes: [
      'project.view', 'engineering.view', 'engineering.approve', 'engineering.reject', 'engineering.comment',
      'qc.view', 'qc.approve', 'qc.reject', 'doc.view', 'doc.download', 'doc.approve', 'doc.reject', 'doc.comment'
    ],
    deniedPermissionCodes: ['invoice.view', 'accounting.view', 'payroll.view', 'hr.view', 'security.view'],
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z'
  }
];

export const SEED_USERS: SecurityUser[] = [
  {
    id: 'usr-admin-01',
    employeeId: 'EMP-001',
    fullName: 'Alexander Vance',
    username: 'superadmin',
    email: 'admin@innovista.com',
    mobile: '+971 50 123 4567',
    userType: 'SUPER_ADMIN',
    adminAuthorityLevel: 'SUPER_ADMINISTRATOR',
    isExternalUser: false,
    organizationId: 'org-inv-hq',
    organizationName: 'Innovista Precision Engineering Corp (Internal HQ)',
    organizationType: 'INTERNAL_HQ',
    department: 'OPERATIONS',
    designation: 'Managing Director & Chief Engineer',
    roleId: 'role-superadmin',
    roleName: 'Super Administrator',
    permissionTemplateId: 'tpl-sys-admin',
    branch: 'Main Store',
    assignedBranches: ['Main Store', 'Dubai Fabrication Yard', 'Abu Dhabi Site Hub', 'Colombo Central Plant', 'Kandy Hub'],
    employmentStatus: 'Full-Time',
    accountStatus: 'Active',
    mfaEnabled: true,
    mfaMethod: 'TOTP',
    recoveryCodesRemaining: 10,
    defaultScope: 'Global',
    assignedProjectIds: ['*'],
    assignedFactoryIds: ['*'],
    failedLoginAttempts: 0,
    lastLogin: '2026-09-26T08:30:00Z',
    lastPasswordChange: '2026-08-01T00:00:00Z',
    onboardingCompleted: true,
    createdBy: 'SYSTEM_BOOTSTRAP',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-09-26T08:30:00Z'
  },
  {
    id: 'usr-pm-01',
    employeeId: 'EMP-042',
    fullName: 'Marcus Sterling',
    username: 'marcus.pm',
    email: 'pm@innovista.com',
    mobile: '+971 52 987 6543',
    userType: 'PROJECT_MANAGER',
    adminAuthorityLevel: 'PROJECT_ADMINISTRATOR',
    isExternalUser: false,
    organizationId: 'org-inv-hq',
    organizationName: 'Innovista Precision Engineering Corp (Internal HQ)',
    organizationType: 'INTERNAL_HQ',
    department: 'OPERATIONS',
    designation: 'Senior Project Manager',
    roleId: 'role-pm',
    roleName: 'Project Manager',
    permissionTemplateId: 'tpl-proj-mgr',
    branch: 'Main Store',
    assignedBranches: ['Main Store', 'Dubai Fabrication Yard', 'Colombo Central Plant'],
    managerName: 'Alexander Vance',
    employmentStatus: 'Full-Time',
    accountStatus: 'Active',
    mfaEnabled: false,
    defaultScope: 'Project',
    assignedProjectIds: ['PRJ-2026-001', 'PRJ-2026-002', 'PRJ-2025-001', 'PRJ-2025-002'],
    assignedFactoryIds: ['fac-inv-01', 'fac-inv-02'],
    failedLoginAttempts: 0,
    lastLogin: '2026-09-26T09:15:00Z',
    lastPasswordChange: '2026-07-15T00:00:00Z',
    onboardingCompleted: true,
    createdBy: 'usr-admin-01',
    createdAt: '2026-01-15T00:00:00Z',
    updatedAt: '2026-09-26T09:15:00Z'
  },
  {
    id: 'usr-fac-01',
    employeeId: 'EMP-051',
    fullName: 'Rohan Wijesinghe',
    username: 'rohan.factory',
    email: 'factory@innovista.com',
    mobile: '+94 77 882 1900',
    userType: 'FACTORY_MANAGER',
    adminAuthorityLevel: 'FACTORY_ADMINISTRATOR',
    isExternalUser: false,
    organizationId: 'org-inv-hq',
    organizationName: 'Innovista Precision Engineering Corp (Internal HQ)',
    organizationType: 'INTERNAL_HQ',
    department: 'FACTORY_PRODUCTION',
    designation: 'Plant & Factory Manager (Supervisor)',
    roleId: 'role-facmgr',
    roleName: 'Factory Manager / Supervisor',
    permissionTemplateId: 'tpl-fac-mgr',
    branch: 'Colombo Central Plant',
    assignedBranches: ['Colombo Central Plant', 'Dubai Fabrication Yard', 'Main Store'],
    managerName: 'Alexander Vance',
    employmentStatus: 'Full-Time',
    accountStatus: 'Active',
    mfaEnabled: false,
    defaultScope: 'Factory',
    assignedProjectIds: ['*'],
    assignedFactoryIds: ['*'],
    failedLoginAttempts: 0,
    lastLogin: '2026-09-26T07:50:00Z',
    lastPasswordChange: '2026-08-05T00:00:00Z',
    onboardingCompleted: true,
    createdBy: 'usr-admin-01',
    createdAt: '2026-01-18T00:00:00Z',
    updatedAt: '2026-09-26T07:50:00Z'
  },
  {
    id: 'usr-fin-01',
    employeeId: 'EMP-018',
    fullName: 'Elena Rostova',
    username: 'elena.fin',
    email: 'finance@innovista.com',
    mobile: '+971 55 456 7890',
    userType: 'FINANCE_MANAGER',
    adminAuthorityLevel: 'DEPARTMENT_ADMINISTRATOR',
    isExternalUser: false,
    organizationId: 'org-inv-hq',
    organizationName: 'Innovista Precision Engineering Corp (Internal HQ)',
    organizationType: 'INTERNAL_HQ',
    department: 'COMMERCIAL_ADMIN',
    designation: 'Financial Controller',
    roleId: 'role-finmgr',
    roleName: 'Finance Manager',
    permissionTemplateId: 'tpl-fin-mgr',
    branch: 'Main Store',
    assignedBranches: ['Main Store', 'Colombo Central Plant'],
    managerName: 'Alexander Vance',
    employmentStatus: 'Full-Time',
    accountStatus: 'Active',
    mfaEnabled: true,
    mfaMethod: 'EMAIL_OTP',
    recoveryCodesRemaining: 8,
    defaultScope: 'Department',
    assignedProjectIds: ['*'],
    assignedFactoryIds: ['fac-inv-01'],
    failedLoginAttempts: 0,
    lastLogin: '2026-09-26T07:45:00Z',
    lastPasswordChange: '2026-08-10T00:00:00Z',
    onboardingCompleted: true,
    createdBy: 'usr-admin-01',
    createdAt: '2026-02-01T00:00:00Z',
    updatedAt: '2026-09-26T07:45:00Z'
  },
  {
    id: 'usr-qc-01',
    employeeId: 'EMP-063',
    fullName: 'David Okafor',
    username: 'david.qc',
    email: 'qc@innovista.com',
    mobile: '+971 54 321 0987',
    userType: 'QA_QC_OFFICER',
    adminAuthorityLevel: 'STANDARD_USER',
    isExternalUser: false,
    organizationId: 'org-inv-hq',
    organizationName: 'Innovista Precision Engineering Corp (Internal HQ)',
    organizationType: 'INTERNAL_HQ',
    department: 'QUALITY',
    designation: 'Senior QA/QC Inspector',
    roleId: 'role-qcinspec',
    roleName: 'Quality Inspector',
    permissionTemplateId: 'tpl-qa-qc',
    branch: 'Dubai Fabrication Yard',
    assignedBranches: ['Dubai Fabrication Yard', 'Colombo Central Plant'],
    managerName: 'Marcus Sterling',
    employmentStatus: 'Full-Time',
    accountStatus: 'Active',
    mfaEnabled: false,
    defaultScope: 'Factory',
    assignedProjectIds: ['PRJ-2026-001', 'PRJ-2025-001'],
    assignedFactoryIds: ['fac-inv-01', 'fac-ext-01'],
    failedLoginAttempts: 0,
    lastLogin: '2026-09-25T11:20:00Z',
    lastPasswordChange: '2026-06-20T00:00:00Z',
    onboardingCompleted: true,
    createdBy: 'usr-admin-01',
    createdAt: '2026-03-01T00:00:00Z',
    updatedAt: '2026-09-25T11:20:00Z'
  },
  {
    id: 'usr-proc-01',
    employeeId: 'EMP-088',
    fullName: 'Tariq Mansoor',
    username: 'tariq.proc',
    email: 'procurement@innovista.com',
    mobile: '+971 56 789 0123',
    userType: 'OPERATIONS_MANAGER',
    adminAuthorityLevel: 'DEPARTMENT_ADMINISTRATOR',
    isExternalUser: false,
    organizationId: 'org-inv-hq',
    organizationName: 'Innovista Precision Engineering Corp (Internal HQ)',
    organizationType: 'INTERNAL_HQ',
    department: 'PROCUREMENT_SUPPLY_CHAIN',
    designation: 'Procurement Director',
    roleId: 'role-procmgr',
    roleName: 'Procurement Manager',
    permissionTemplateId: 'tpl-ops-mgr',
    branch: 'Main Store',
    assignedBranches: ['Main Store', 'Dubai Fabrication Yard'],
    managerName: 'Alexander Vance',
    employmentStatus: 'Full-Time',
    accountStatus: 'Active',
    mfaEnabled: false,
    defaultScope: 'Department',
    assignedProjectIds: ['*'],
    assignedFactoryIds: ['fac-inv-01', 'fac-inv-02'],
    failedLoginAttempts: 0,
    lastLogin: '2026-09-25T09:00:00Z',
    lastPasswordChange: '2026-07-01T00:00:00Z',
    onboardingCompleted: true,
    createdBy: 'usr-admin-01',
    createdAt: '2026-03-10T00:00:00Z',
    updatedAt: '2026-09-25T09:00:00Z'
  },
  {
    id: 'usr-qs-01',
    employeeId: 'EMP-031',
    fullName: 'Julian Chen',
    username: 'julian.qs',
    email: 'qs@innovista.com',
    mobile: '+971 50 876 5432',
    userType: 'QS',
    adminAuthorityLevel: 'STANDARD_USER',
    isExternalUser: false,
    organizationId: 'org-inv-hq',
    organizationName: 'Innovista Precision Engineering Corp (Internal HQ)',
    organizationType: 'INTERNAL_HQ',
    department: 'ENGINEERING',
    designation: 'Chief Quantity Surveyor',
    roleId: 'role-qs',
    roleName: 'QS (Quantity Surveyor)',
    permissionTemplateId: 'tpl-qs-eng',
    branch: 'Main Store',
    assignedBranches: ['Main Store'],
    managerName: 'Alexander Vance',
    employmentStatus: 'Full-Time',
    accountStatus: 'Active',
    mfaEnabled: false,
    defaultScope: 'Department',
    assignedProjectIds: ['PRJ-2026-001', 'PRJ-2026-002', 'PRJ-2025-001'],
    assignedFactoryIds: ['fac-inv-01'],
    failedLoginAttempts: 0,
    lastLogin: '2026-09-26T06:10:00Z',
    lastPasswordChange: '2026-08-15T00:00:00Z',
    onboardingCompleted: true,
    createdBy: 'usr-admin-01',
    createdAt: '2026-02-15T00:00:00Z',
    updatedAt: '2026-09-26T06:10:00Z'
  },
  {
    id: 'usr-hr-01',
    employeeId: 'EMP-055',
    fullName: 'Sara Jenkins',
    username: 'sara.hr',
    email: 'hr@innovista.com',
    mobile: '+971 50 123 9876',
    userType: 'HR_MANAGER',
    adminAuthorityLevel: 'DEPARTMENT_ADMINISTRATOR',
    isExternalUser: false,
    organizationId: 'org-inv-hq',
    organizationName: 'Innovista Precision Engineering Corp (Internal HQ)',
    organizationType: 'INTERNAL_HQ',
    department: 'COMMERCIAL_ADMIN',
    designation: 'Human Resources Director',
    roleId: 'role-hrmgr',
    roleName: 'HR Manager',
    permissionTemplateId: 'tpl-hr-mgr',
    branch: 'Main Store',
    assignedBranches: ['Main Store', 'Dubai Fabrication Yard', 'Colombo Central Plant'],
    managerName: 'Alexander Vance',
    employmentStatus: 'Full-Time',
    accountStatus: 'Active',
    mfaEnabled: false,
    defaultScope: 'Department',
    assignedProjectIds: ['*'],
    assignedFactoryIds: ['fac-inv-01', 'fac-inv-02'],
    failedLoginAttempts: 0,
    lastLogin: '2026-09-25T08:30:00Z',
    lastPasswordChange: '2026-07-20T00:00:00Z',
    onboardingCompleted: true,
    createdBy: 'usr-admin-01',
    createdAt: '2026-02-20T00:00:00Z',
    updatedAt: '2026-09-25T08:30:00Z'
  },
  // EXTERNAL MULTI-TENANT USERS (External Factory, Customer, Supplier, Consultant)
  {
    id: 'usr-ext-fac-01',
    employeeId: 'EXT-FAC-101',
    fullName: 'Hassan Al-Maktoum',
    username: 'hassan.partner',
    email: 'hassan@alfuttaim-metal.ae',
    mobile: '+971 50 998 1122',
    userType: 'EXTERNAL_FACTORY_MANAGER',
    adminAuthorityLevel: 'FACTORY_ADMINISTRATOR',
    isExternalUser: true,
    organizationId: 'org-ext-fac-01',
    organizationName: 'Al-Futtaim Architectural Metalworks LLC',
    organizationType: 'EXTERNAL_FACTORY',
    department: 'FACTORY_PRODUCTION',
    designation: 'External Partner Plant Director',
    roleId: 'role-ext-fac-mgr',
    roleName: 'External Partner Factory Manager',
    permissionTemplateId: 'tpl-ext-fac-mgr',
    branch: 'Dubai Fabrication Yard',
    assignedBranches: ['Dubai Fabrication Yard'],
    managerName: 'Marcus Sterling',
    employmentStatus: 'External Partner',
    accountStatus: 'Active',
    mfaEnabled: false,
    defaultScope: 'Factory',
    authorizedPortalIds: ['partner-factory-portal', 'factory-workshop-management', 'document-control'],
    assignedProjectIds: ['PRJ-2026-001'],
    deniedProjectIds: ['PRJ-2026-002', 'PRJ-2026-003'],
    assignedFactoryIds: ['fac-ext-01'],
    deniedFactoryIds: ['fac-inv-01', 'fac-inv-02', 'fac-ext-02'],
    failedLoginAttempts: 0,
    lastLogin: '2026-09-26T08:10:00Z',
    lastPasswordChange: '2026-08-20T00:00:00Z',
    onboardingCompleted: true,
    createdBy: 'usr-admin-01',
    createdAt: '2026-02-16T00:00:00Z',
    updatedAt: '2026-09-26T08:10:00Z'
  },
  {
    id: 'usr-cust-01',
    employeeId: 'EXT-CLI-201',
    fullName: 'Vikram Rajapaksa',
    username: 'vikram.client',
    email: 'vikram@sapphiretowers.lk',
    mobile: '+94 77 233 9900',
    userType: 'B2B_CLIENT',
    adminAuthorityLevel: 'STANDARD_USER',
    isExternalUser: true,
    organizationId: 'org-cust-01',
    organizationName: 'Sapphire Towers Development PLC (B2B Client)',
    organizationType: 'B2B_CLIENT',
    department: 'COMMERCIAL_ADMIN',
    designation: 'Client Executive Representative',
    roleId: 'role-customer',
    roleName: 'Client / Customer Representative',
    permissionTemplateId: 'tpl-customer',
    branch: 'Colombo Central Plant',
    assignedBranches: ['Colombo Central Plant'],
    employmentStatus: 'Customer Account',
    accountStatus: 'Active',
    mfaEnabled: false,
    defaultScope: 'Organization',
    authorizedPortalIds: ['customer-portal', 'document-control'],
    assignedProjectIds: ['PRJ-2026-001'],
    deniedProjectIds: ['PRJ-2026-002', 'PRJ-2026-003'],
    assignedFactoryIds: [],
    failedLoginAttempts: 0,
    lastLogin: '2026-09-25T17:05:00Z',
    lastPasswordChange: '2026-08-12T00:00:00Z',
    onboardingCompleted: true,
    createdBy: 'usr-admin-01',
    createdAt: '2026-01-22T00:00:00Z',
    updatedAt: '2026-09-25T17:05:00Z'
  },
  {
    id: 'usr-sup-01',
    employeeId: 'EXT-SUP-301',
    fullName: 'Karim El-Masri',
    username: 'karim.supplier',
    email: 'karim@gulfextrusions.ae',
    mobile: '+971 50 884 6600',
    userType: 'SUPPLIER',
    adminAuthorityLevel: 'STANDARD_USER',
    isExternalUser: true,
    organizationId: 'org-sup-01',
    organizationName: 'Gulf Extrusions & Architectural Glass Co.',
    organizationType: 'SUPPLIER',
    department: 'PROCUREMENT_SUPPLY_CHAIN',
    designation: 'Key Account Supply Director',
    roleId: 'role-supplier',
    roleName: 'External Supplier / Vendor Representative',
    permissionTemplateId: 'tpl-supplier',
    branch: 'Main Store',
    assignedBranches: ['Main Store'],
    employmentStatus: 'External Partner',
    accountStatus: 'Active',
    mfaEnabled: false,
    defaultScope: 'Organization',
    authorizedPortalIds: ['supplier-portal'],
    assignedProjectIds: ['PRJ-2026-001', 'PRJ-2026-002'],
    assignedFactoryIds: [],
    failedLoginAttempts: 0,
    lastLogin: '2026-09-24T14:20:00Z',
    lastPasswordChange: '2026-07-29T00:00:00Z',
    onboardingCompleted: true,
    createdBy: 'usr-proc-01',
    createdAt: '2026-02-05T00:00:00Z',
    updatedAt: '2026-09-24T14:20:00Z'
  },
  {
    id: 'usr-lock-01',
    employeeId: 'EMP-104',
    fullName: 'Samir Al-Nasser',
    username: 'samir.site',
    email: 'samir@innovista.com',
    mobile: '+971 52 333 4444',
    userType: 'SITE_SUPERVISOR',
    adminAuthorityLevel: 'STANDARD_USER',
    isExternalUser: false,
    organizationId: 'org-inv-hq',
    organizationName: 'Innovista Precision Engineering Corp (Internal HQ)',
    organizationType: 'INTERNAL_HQ',
    department: 'OPERATIONS',
    designation: 'Site Supervisor',
    roleId: 'role-sitesup',
    roleName: 'Site Supervisor',
    permissionTemplateId: 'tpl-site-sup',
    branch: 'Abu Dhabi Site Hub',
    assignedBranches: ['Abu Dhabi Site Hub'],
    managerName: 'Marcus Sterling',
    employmentStatus: 'Full-Time',
    accountStatus: 'Locked',
    mfaEnabled: false,
    defaultScope: 'Project',
    assignedProjectIds: ['PRJ-2026-002', 'PRJ-2025-002'],
    assignedFactoryIds: [],
    failedLoginAttempts: 5,
    lockedUntil: '2026-09-27T12:00:00Z',
    lastPasswordChange: '2026-05-10T00:00:00Z',
    onboardingCompleted: true,
    createdBy: 'usr-admin-01',
    createdAt: '2026-04-01T00:00:00Z',
    updatedAt: '2026-09-26T08:00:00Z'
  }
];

export const SEED_SOD_RULES: SegregationOfDutyRule[] = [
  {
    id: 'sod-01',
    ruleCode: 'SOD-PO-PAY',
    ruleName: 'PO Creation vs Payment Approval',
    description: 'A user cannot create or authorize purchase orders and simultaneously disburse accounts payable funds.',
    conflictingPermissionA: 'po.create',
    conflictingPermissionB: 'invoice.approve',
    severity: 'Strict Block',
    isActive: true
  },
  {
    id: 'sod-02',
    ruleCode: 'SOD-PO-GRN',
    ruleName: 'Purchasing vs Goods Received Sign-off',
    description: 'Procurement officers initiating POs cannot record physical goods acceptance at the warehouse gate.',
    conflictingPermissionA: 'po.approve',
    conflictingPermissionB: 'grn.approve',
    severity: 'Strict Block',
    isActive: true
  },
  {
    id: 'sod-03',
    ruleCode: 'SOD-QC-CLOSE',
    ruleName: 'NCR Inception vs Unilateral Closure',
    description: 'An inspector who issues a Non-Conformance Report cannot close it without Quality Manager concurrence.',
    conflictingPermissionA: 'qc.create',
    conflictingPermissionB: 'qc.approve',
    severity: 'Warning',
    isActive: true
  },
  {
    id: 'sod-04',
    ruleCode: 'SOD-VAR-EST',
    ruleName: 'BOQ Rate Formulation vs Budget Release',
    description: 'Quantity Surveyors editing base BOQ rates cannot unilaterally approve client invoice variations above $50k.',
    conflictingPermissionA: 'boq.edit',
    conflictingPermissionB: 'project.approve',
    severity: 'Warning',
    isActive: true
  },
  {
    id: 'sod-05',
    ruleCode: 'SOD-SEC-SELF',
    ruleName: 'Privilege Modification vs Audit Trail Administration',
    description: 'Administrators modifying RBAC role permissions cannot purge or unlock immutable security audit trails.',
    conflictingPermissionA: 'security.admin',
    conflictingPermissionB: 'audit.delete',
    severity: 'Strict Block',
    isActive: true
  },
  {
    id: 'sod-06',
    ruleCode: 'SOD-PAY-HR',
    ruleName: 'Employee Master Salary Edit vs Final WPS Bank Release',
    description: 'HR officers modifying employee base salary structures cannot unilaterally release the final bank payroll disbursement.',
    conflictingPermissionA: 'hr.edit',
    conflictingPermissionB: 'payroll.approve',
    severity: 'Strict Block',
    isActive: true
  }
];

export const SEED_SESSIONS: UserSession[] = [
  {
    id: 'sess-01',
    userId: 'usr-admin-01',
    username: 'superadmin',
    fullName: 'Alexander Vance',
    userType: 'SUPER_ADMIN',
    roleName: 'Super Administrator',
    device: 'MacBook Pro 16" (M3 Max)',
    browser: 'Chrome 128.0',
    os: 'macOS Sonoma',
    ipAddress: '194.170.21.84',
    location: 'Dubai, United Arab Emirates',
    authMethod: 'Password + TOTP MFA',
    isSuspicious: false,
    lastActivity: 'Just now',
    loginTime: '2026-09-26T08:30:00Z',
    isCurrent: true,
    expiresAt: '2026-09-27T08:30:00Z'
  },
  {
    id: 'sess-02',
    userId: 'usr-fac-01',
    username: 'rohan.factory',
    fullName: 'Rohan Wijesinghe',
    userType: 'FACTORY_MANAGER',
    roleName: 'Factory Manager',
    device: 'Rugged Industrial Tablet (Bay 01)',
    browser: 'Safari Mobile 18.0',
    os: 'iPadOS 18.1',
    ipAddress: '112.134.88.19',
    location: 'Colombo Central Fabrication Plant',
    authMethod: 'Direct Terminal',
    isSuspicious: false,
    lastActivity: '14 minutes ago',
    loginTime: '2026-09-26T06:15:00Z',
    isCurrent: false,
    expiresAt: '2026-09-27T06:15:00Z'
  },
  {
    id: 'sess-03',
    userId: 'usr-pm-01',
    username: 'marcus.pm',
    fullName: 'Marcus Sterling',
    userType: 'PROJECT_MANAGER',
    roleName: 'Project Manager',
    device: 'Dell Precision 7780 Workstation',
    browser: 'Firefox 130.0',
    os: 'Windows 11 Enterprise',
    ipAddress: '194.170.21.85',
    location: 'Fabrication Yard Site Office',
    authMethod: 'SSO Corporate',
    isSuspicious: false,
    lastActivity: '32 minutes ago',
    loginTime: '2026-09-26T07:10:00Z',
    isCurrent: false,
    expiresAt: '2026-09-27T07:10:00Z'
  },
  {
    id: 'sess-04',
    userId: 'usr-ext-fac-01',
    username: 'hassan.partner',
    fullName: 'Hassan Al-Maktoum',
    userType: 'EXTERNAL_FACTORY_MANAGER',
    roleName: 'External Partner Factory Manager',
    device: 'Surface Pro 10 Enterprise',
    browser: 'Edge 128.0',
    os: 'Windows 11 Pro',
    ipAddress: '185.93.22.10',
    location: 'Jebel Ali Industrial Zone (External Partner Plant)',
    authMethod: 'Password + Email OTP',
    isSuspicious: false,
    lastActivity: '8 minutes ago',
    loginTime: '2026-09-26T08:10:00Z',
    isCurrent: false,
    expiresAt: '2026-09-27T08:10:00Z'
  }
];

export const SEED_ACCESS_REQUESTS: AccessRequest[] = [
  {
    id: 'req-101',
    requestNumber: 'REQ-2026-0041',
    requesterId: 'usr-pm-01',
    requesterName: 'Marcus Sterling',
    requesterRole: 'Project Manager',
    requesterDepartment: 'OPERATIONS',
    requestType: 'Portal Access',
    requestedItem: 'Portal: Procurement & Supply Chain (procurement-supply-chain)',
    targetPortalId: 'procurement-supply-chain',
    targetProjectId: 'PRJ-2026-003',
    requestedPermissionCodes: ['po.view', 'rfq.view', 'supplier.view', 'grn.view'],
    riskLevel: 'Medium',
    requiresDualApproval: false,
    currentLevel: 'Projects, Site, Factory & Quality Portals Only',
    requestedLevel: 'Procurement Portal & PO/RFQ Visibility + PRJ-2026-003 Scope',
    justification: 'Assigned as lead PM to track long-lead facade extrusion POs and supplier RFQs.',
    duration: 'Temporary (30 days)',
    status: 'Pending Review',
    createdAt: '2026-09-26T07:15:00Z'
  },
  {
    id: 'req-102',
    requestNumber: 'REQ-2026-0042',
    requesterId: 'usr-ext-fac-01',
    requesterName: 'Hassan Al-Maktoum',
    requesterRole: 'External Partner Factory Manager',
    requesterDepartment: 'FACTORY_PRODUCTION',
    requestType: 'Factory Access',
    requestedItem: 'Work Package FWP-2026-003 & Production BOM Portal (production-control)',
    targetPortalId: 'production-control',
    targetFactoryId: 'fac-ext-01',
    targetProjectId: 'PRJ-2026-002',
    requestedPermissionCodes: ['engineering.view', 'boq.view'],
    riskLevel: 'High',
    requiresDualApproval: true,
    currentLevel: 'Factory: fac-ext-01 (PRJ-2026-001 Only)',
    requestedLevel: 'Production Control Portal + External Fabricator Scope on PRJ-2026-002',
    justification: 'Overflow sub-contracting package awarded to Al-Futtaim Metalworks for Q4 steel canopy delivery.',
    duration: 'Temporary (90 days)',
    status: 'Pending Review',
    createdAt: '2026-09-26T08:40:00Z'
  },
  {
    id: 'req-103',
    requestNumber: 'REQ-2026-0039',
    requesterId: 'usr-qs-01',
    requesterName: 'Julian Chen',
    requesterRole: 'QS (Quantity Surveyor)',
    requesterDepartment: 'ENGINEERING',
    requestType: 'Portal Access',
    requestedItem: 'Procurement Supplier Directory & Rates Portal (procurement-supply-chain)',
    targetPortalId: 'procurement-supply-chain',
    requestedPermissionCodes: ['supplier.view', 'rfq.view', 'po.view'],
    riskLevel: 'Medium',
    requiresDualApproval: false,
    currentLevel: 'Engineering & QS BOQ Portals Only',
    requestedLevel: 'Procurement Portal Read Access (supplier.view, rfq.view, po.view)',
    justification: 'Conducting Q3 benchmark variance study comparing sub-contractor steel offers.',
    duration: 'Temporary (7 days)',
    status: 'Pending Review',
    createdAt: '2026-09-25T11:00:00Z'
  }
];

export const SEED_DELEGATIONS: PermissionDelegation[] = [
  {
    id: 'del-01',
    delegatorId: 'usr-pm-01',
    delegatorName: 'Marcus Sterling',
    delegatorRole: 'Project Manager',
    delegateeId: 'usr-qs-01',
    delegateeName: 'Julian Chen',
    delegateeRole: 'QS (Quantity Surveyor)',
    delegatedPermissions: ['boq.approve', 'project.submit'],
    scope: 'Project',
    startDate: '2026-09-20',
    endDate: '2026-09-30',
    reason: 'Site inspection travel to Saudi Arabia Gigaproject site for tender handover.',
    status: 'Active',
    approvedBy: 'Alexander Vance',
    createdAt: '2026-09-18T10:00:00Z'
  }
];

export const SEED_AUDIT_LOGS: SecurityAuditEvent[] = [
  {
    id: 'aud-001',
    userId: 'usr-admin-01',
    username: 'superadmin',
    userFullName: 'Alexander Vance',
    userRole: 'Super Administrator',
    portalId: 'system-administration',
    moduleName: 'Authentication Service',
    action: 'LOGIN_SUCCESS',
    target: 'Central Identity Provider',
    details: 'MFA challenge verified via TOTP Authenticator App. Session token issued.',
    ipAddress: '194.170.21.84',
    device: 'MacBook Pro 16" (macOS)',
    severity: 'Info',
    timestamp: '2026-09-26T08:30:00Z'
  },
  {
    id: 'aud-002',
    userId: 'usr-ext-fac-01',
    username: 'hassan.partner',
    userFullName: 'Hassan Al-Maktoum',
    userRole: 'External Partner Factory Manager',
    portalId: 'factory-workshop-management',
    moduleName: 'Factories Master & Project Assignment',
    action: 'ACCESS_DENIED_ATTEMPT',
    target: 'Factory: fac-inv-01 (Innovista Internal Plant)',
    details: 'Central Permission Engine blocked cross-factory query: User organization ORG-EXT-FAC-01 is isolated to fac-ext-01.',
    ipAddress: '185.93.22.10',
    device: 'Surface Pro 10 (Windows)',
    severity: 'Warning',
    timestamp: '2026-09-26T08:14:22Z'
  },
  {
    id: 'aud-003',
    userId: 'usr-lock-01',
    username: 'samir.site',
    userFullName: 'Samir Al-Nasser',
    userRole: 'Site Supervisor',
    portalId: 'construction-site-management',
    moduleName: 'Authentication Gateway',
    action: 'ACCOUNT_LOCKED',
    target: 'User Account: usr-lock-01',
    details: 'Account locked automatically: 5 consecutive invalid password attempts exceeded policy threshold.',
    ipAddress: '91.73.18.204',
    device: 'Android 14 / Chrome Mobile',
    severity: 'Security Alert',
    timestamp: '2026-09-26T08:00:15Z'
  },
  {
    id: 'aud-004',
    userId: 'usr-admin-01',
    username: 'superadmin',
    userFullName: 'Alexander Vance',
    userRole: 'Super Administrator',
    portalId: 'system-administration',
    moduleName: 'Delegation & Emergency Governance',
    action: 'DELEGATION_CREATED',
    target: 'Delegation: Marcus Sterling -> Julian Chen',
    details: 'Temporary authority for boq.approve granted until 2026-09-30.',
    ipAddress: '194.170.21.84',
    device: 'MacBook Pro 16" (macOS)',
    severity: 'Info',
    timestamp: '2026-09-18T10:00:00Z'
  },
  {
    id: 'aud-005',
    userId: 'usr-fin-01',
    username: 'elena.fin',
    userFullName: 'Elena Rostova',
    userRole: 'Finance Manager',
    portalId: 'accounting-finance',
    moduleName: 'Invoicing & Receivables Ledger',
    action: 'DATA_EXPORT',
    target: 'Q3 VAT & Retention Ledger',
    oldValue: 'Unexported Ledger State',
    newValue: 'Exported 48 verified records (XLSX)',
    details: 'Exported quarterly VAT statement after MFA verification.',
    ipAddress: '194.170.21.90',
    device: 'ThinkPad X1 Carbon (Windows)',
    severity: 'Info',
    timestamp: '2026-09-25T15:22:00Z'
  },
  {
    id: 'aud-006',
    userId: 'usr-qc-01',
    username: 'david.qc',
    userFullName: 'David Okafor',
    userRole: 'Quality Inspector',
    portalId: 'quality-assurance',
    moduleName: 'Mill Test Certificates',
    action: 'CONFIDENTIAL_ACCESS',
    target: 'Document: Mill Test Certificate #MTC-8892',
    details: 'Viewed classified material metallurgical lab certificate for Project PRJ-2026-001.',
    ipAddress: '194.170.21.88',
    device: 'iPad Air (iOS)',
    severity: 'Info',
    timestamp: '2026-09-25T09:14:00Z'
  }
];
