import { Quote, CompanySettings, QuoteStatus, DEFAULT_TERMS, Client, CustomerCategory, Invoice, InvoiceType, InvoiceStatus } from './types';

export const INITIAL_QUOTE: Quote = {
  id: '',
  quoteNo: `QT-${new Date().getFullYear()}-${Math.floor(1000 + Math.random() * 9000)}`,
  projectId: '',
  projectCode: '',
  projectName: '',
  workSiteLocation: '',
  salesRepresentative: '',
  quoteType: 'Detailed BOQ',
  pricingMethod: 'Unit Rate',
  projectStage: 'Detailed BOQ',
  scopeCoverage: 'Supply & Install',
  version: 1,
  submittedDate: new Date().toISOString().split('T')[0],
  validityDays: 15,
  validUntil: new Date(Date.now() + 15 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
  currency: 'Rs.',
  client: {
    id: '',
    category: CustomerCategory.INDIVIDUAL,
    name: '',
    phone: '',
    address: '',
    email: '',
    status: 'Active',
    creditLimit: 0,
    paymentTerms: '',
    currency: 'LKR',
    language: 'English',
    sinceDate: new Date().toISOString().split('T')[0],
    contactPersons: [],
    addresses: [],
    source: 'Direct',
    tier: 'Tier 1',
    isCommHidden: true,
    isTaxExempt: false,
    hasSpecialPricing: false,
    tags: [],
    classification: ''
  },
  items: [],
  terms: DEFAULT_TERMS,
  additionalCharges: [],
  discountPercent: 0,
  taxPercent: 0,
  isTaxInclusive: false,
  advancePercent: 60,
  estimatedDeliveryDays: 5,
  status: QuoteStatus.DRAFT,
  marginPercent: 15,
  lumpSumAmount: 0,
  timeline: { id: crypto.randomUUID(), quoteId: '', jobs: [] },
  declaration: "I assure you of my best service at all times, and I await your Order Confirmation and Advance Payment, enabling us to commence work early.\nI. We are inviting you to sign a contract agreement to ensure the trustworthy and legal protection between the contractor or bidder and the customer or client.\nII. Then, if you would like to sign the proposed agreement, we have attached a copy of contract agreement, including details and conditions of the contract as follows. So please be kind enough to read carefully.",
  documentSettings: {
    fontSize: 10,
    accentColor: '#2563eb',
    showLogo: true,
    showBankDetails: true,
    showTimeline: false,
    showPaymentTiers: true,
    layoutType: 'Detailed'
  },
  paymentTiers: [
    { id: crypto.randomUUID(), phase: 'Advance Payment', percentage: 60, amount: 0, status: 'Pending' },
    { id: crypto.randomUUID(), phase: 'Progress Payment', percentage: 20, amount: 0, status: 'Pending' },
    { id: crypto.randomUUID(), phase: 'Final Payment', percentage: 20, amount: 0, status: 'Pending' }
  ]
};

export const INITIAL_COMPANY_SETTINGS: CompanySettings = {
  name: 'Innovista Metal',
  address: 'Kelaniya, Sri Lanka',
  phone: '0773726224',
  email: 'innovistametal@gmail.com',
  website: 'www.innovistametal.com',
  bankDetails: [
    {
      id: crypto.randomUUID(),
      bankName: 'Commercial Bank',
      branchName: 'Kelaniya',
      accountName: 'Innovista Metal (Pvt) Ltd',
      accountNumber: '1234567890',
      swiftCode: 'COMBPCE',
      isDefault: true
    }
  ],
  currencies: ['LKR', 'USD', 'EUR', 'GBP', 'AED'],
  defaultCurrency: 'LKR',
  quoteNumberPrefix: `QT-${new Date().getFullYear()}-`,
  nextQuoteNumber: 1001,
  invoiceNumberPrefix: `INV-${new Date().getFullYear()}-`,
  nextInvoiceNumber: 1001,
  defaultValidityDays: 15,
  defaultDeliveryDays: 21,
  enableNotifications: true,
  vatNo: '123456789-7000',
  defaultRetentionPercent: 5,
  retentionClauses: 'I. 5% retention will be deducted from each progress payment.\nII. Retention will be released after the defect liability period.'
};

export const SAMPLE_CLIENTS: Client[] = [
  {
    id: 'c1',
    category: CustomerCategory.COMPANY,
    name: 'Metropolitan Real Estate',
    tradeName: 'METRO HOMES',
    registrationNo: 'PV-123456',
    taxNo: '100234567-0000',
    industry: 'Real Estate',
    status: 'Active',
    creditLimit: 5000000,
    paymentTerms: '30 Days Net',
    currency: 'LKR',
    language: 'English',
    sinceDate: '2023-01-15',
    email: 'projects@metrohomes.lk',
    phone: '+94 11 234 5678',
    address: '45, Galle Road, Colombo 03, Sri Lanka',
    website: 'www.metrohomes.lk',
    contactPersons: [
      {
        id: 'cp1',
        name: 'John Perera',
        jobTitle: 'Project Manager',
        email: 'john@metrohomes.lk',
        phone: '+94 11 234 5679',
        mobile: '+94 77 123 4567',
        isPrimary: true,
        canApproveQuotes: true,
        canReceiveInvoices: false,
        preferredContact: 'Email'
      }
    ],
    addresses: [
      {
        id: 'a1',
        label: 'Registered Office',
        street: '45, Galle Road',
        city: 'Colombo 03',
        state: 'Western',
        postalCode: '00300',
        country: 'Sri Lanka'
      }
    ],
    source: 'Direct',
    tier: 'Tier 1',
    isCommHidden: true,
    isTaxExempt: false,
    hasSpecialPricing: false,
    tags: ['VIP', 'Luxury'],
    classification: 'Corporate'
  },
  {
    id: 'c2',
    category: CustomerCategory.INDIVIDUAL,
    name: 'Dr. Michael Fernando',
    registrationNo: '851234567V',
    status: 'Active',
    creditLimit: 1000000,
    paymentTerms: 'Payment on Completion',
    currency: 'LKR',
    language: 'English',
    sinceDate: '2023-06-20',
    email: 'micheal@medical.lk',
    phone: '+94 76 123 4567',
    address: '12/A, Flower Road, Colombo 07',
    contactPersons: [],
    addresses: [
      {
        id: 'a3',
        label: 'Shipping',
        street: '12/A, Flower Road',
        city: 'Colombo 07',
        state: 'Western',
        postalCode: '00700',
        country: 'Sri Lanka'
      }
    ],
    source: 'Walk-in',
    tier: 'Tier 2',
    isCommHidden: true,
    isTaxExempt: false,
    hasSpecialPricing: false,
    tags: ['Individual', 'Premium'],
    classification: 'Residential'
  }
];

export const SAMPLE_PROJECTS: any[] = [
  {
    id: 'proj-altair-01',
    projectName: 'Altair Tower - Luxury Façade & Glazing Package',
    originalQuoteNo: 'QT-2026-1042',
    startDate: '2026-01-15',
    status: 'In Progress',
    totalValue: 3450000,
    currency: 'Rs.',
    client: SAMPLE_CLIENTS[0],
    items: [
      {
        id: 'boq-item-101',
        no: '1.0',
        name: 'Curtain Wall System (Double Glazed Low-E)',
        description: 'Thermally broken aluminium mullions & transoms with 24mm DGU Low-E glass panels',
        itemType: 'Main',
        category: 'Aluminium',
        unit: 'sqft',
        qty: 450,
        rate: 4200,
        discountPercent: 0,
        amount: 1890000,
        variantCode: 'AL-CW-001',
        costAtTimeOfQuote: 2950,
        variationStatus: 'Original'
      },
      {
        id: 'boq-item-102',
        no: '2.0',
        name: 'Heavy Duty Sliding Balcony Doors',
        description: 'Euro-groove 3-track sliding door system with multi-point flush shootbolts',
        itemType: 'Main',
        category: 'Aluminium',
        unit: 'sqft',
        qty: 240,
        rate: 3800,
        discountPercent: 0,
        amount: 912000,
        variantCode: 'AL-DR-003',
        costAtTimeOfQuote: 2650,
        variationStatus: 'Original'
      },
      {
        id: 'boq-item-103',
        no: '3.0',
        name: 'Frameless Glass Balustrade (15mm Tempered)',
        description: 'Bottom aluminium shoe channel with continuous LED recess and 15mm clear tempered glass',
        itemType: 'Main',
        category: 'Glass',
        unit: 'L.ft',
        qty: 120,
        rate: 5400,
        discountPercent: 0,
        amount: 648000,
        variantCode: 'GL-BL-001',
        costAtTimeOfQuote: 3800,
        variationStatus: 'Original'
      }
    ],
    terms: DEFAULT_TERMS,
    paymentTiers: [
      { id: 'pt-1', phase: 'Advance Payment', percentage: 30, amount: 1035000, status: 'Paid' },
      { id: 'pt-2', phase: 'Materials Procurement', percentage: 40, amount: 1380000, status: 'Paid' },
      { id: 'pt-3', phase: 'Testing & Handover', percentage: 30, amount: 1035000, status: 'Pending' }
    ]
  },
  {
    id: 'proj-portcity-02',
    projectName: 'Port City Marine Terminal - Acoustic Partitions & Louvers',
    originalQuoteNo: 'QT-2026-1088',
    startDate: '2026-02-01',
    status: 'In Progress',
    totalValue: 2180000,
    currency: 'Rs.',
    client: SAMPLE_CLIENTS[1],
    items: [
      {
        id: 'boq-item-201',
        no: '1.0',
        name: 'Acoustic Soundproof Glass Partitions',
        description: 'Double glazed 12mm + acoustic PVB + 10mm partition with perimeter neoprene seals',
        itemType: 'Main',
        category: 'Glass',
        unit: 'sqft',
        qty: 320,
        rate: 4500,
        discountPercent: 0,
        amount: 1440000,
        variantCode: 'GL-AC-002',
        costAtTimeOfQuote: 3100,
        variationStatus: 'Original'
      },
      {
        id: 'boq-item-202',
        no: '2.0',
        name: 'Aerodynamic Architectural Louver Screen',
        description: 'Z-profile architectural extruded aluminium storm louvers with bird mesh',
        itemType: 'Main',
        category: 'Aluminium',
        unit: 'sqft',
        qty: 200,
        rate: 3700,
        discountPercent: 0,
        amount: 740000,
        variantCode: 'AL-LV-004',
        costAtTimeOfQuote: 2550,
        variationStatus: 'Original'
      }
    ],
    terms: DEFAULT_TERMS,
    paymentTiers: [
      { id: 'pt-21', phase: 'Mobilization', percentage: 40, amount: 872000, status: 'Paid' },
      { id: 'pt-22', phase: 'Site Erection', percentage: 60, amount: 1308000, status: 'Pending' }
    ]
  },
  {
    id: 'proj-cinnamon-03',
    projectName: 'Cinnamon Life Suites - Acoustic Glazing & Partitions',
    originalQuoteNo: 'QT-2025-0891',
    startDate: '2025-08-10',
    status: 'Completed',
    totalValue: 5200000,
    currency: 'Rs.',
    client: SAMPLE_CLIENTS[0],
    items: [
      {
        id: 'boq-item-301',
        no: '1.0',
        name: 'Thermally Broken Acoustic Sliding Doors',
        description: 'Multi-point euro-groove acoustic slide doors with argon gas filled double glazing',
        itemType: 'Main',
        category: 'Aluminium',
        unit: 'sqft',
        qty: 600,
        rate: 5500,
        discountPercent: 0,
        amount: 3300000,
        variantCode: 'AL-DR-003',
        costAtTimeOfQuote: 3600,
        variationStatus: 'Original'
      },
      {
        id: 'boq-item-302',
        no: '2.0',
        name: 'Internal Acoustic Glass Office Partitions',
        description: '12.38mm acoustic laminated glass with black powder-coated aluminium slim profile',
        itemType: 'Main',
        category: 'Glass',
        unit: 'sqft',
        qty: 380,
        rate: 5000,
        discountPercent: 0,
        amount: 1900000,
        variantCode: 'GL-AC-002',
        costAtTimeOfQuote: 3300,
        variationStatus: 'Original'
      }
    ],
    terms: DEFAULT_TERMS,
    paymentTiers: [
      { id: 'pt-31', phase: 'Advance Payment', percentage: 50, amount: 2600000, status: 'Paid' },
      { id: 'pt-32', phase: 'Final Handover', percentage: 50, amount: 2600000, status: 'Paid' }
    ]
  },
  {
    id: 'proj-havelock-04',
    projectName: 'Havelock City Phase 4 - Balustrades & Glass Railings',
    originalQuoteNo: 'QT-2025-0940',
    startDate: '2025-09-01',
    status: 'Completed',
    totalValue: 3100000,
    currency: 'Rs.',
    client: SAMPLE_CLIENTS[1],
    items: [
      {
        id: 'boq-item-401',
        no: '1.0',
        name: 'Frameless Glass Balustrade (15mm Tempered)',
        description: 'Continuous bottom shoe channel with LED lighting recess and 15mm clear tempered safety glass',
        itemType: 'Main',
        category: 'Glass',
        unit: 'L.ft',
        qty: 550,
        rate: 5636,
        discountPercent: 0,
        amount: 3100000,
        variantCode: 'GL-BL-001',
        costAtTimeOfQuote: 3850,
        variationStatus: 'Original'
      }
    ],
    terms: DEFAULT_TERMS,
    paymentTiers: [
      { id: 'pt-41', phase: 'Advance Payment', percentage: 50, amount: 1550000, status: 'Paid' },
      { id: 'pt-42', phase: 'Final Handover', percentage: 50, amount: 1550000, status: 'Paid' }
    ]
  },
  {
    id: 'proj-shangrila-05',
    projectName: 'Shangri-La Commercial Mall - Main Storefronts',
    originalQuoteNo: 'QT-2025-0722',
    startDate: '2025-07-15',
    status: 'Completed',
    totalValue: 7400000,
    currency: 'Rs.',
    client: SAMPLE_CLIENTS[0],
    items: [
      {
        id: 'boq-item-501',
        no: '1.0',
        name: 'Commercial Storefront Framing & Glass',
        description: 'Structural spider glass fittings with 19mm ultra-clear low-iron tempered glass',
        itemType: 'Main',
        category: 'Glass',
        unit: 'sqft',
        qty: 900,
        rate: 5800,
        discountPercent: 0,
        amount: 5220000,
        variantCode: 'GL-CW-002',
        costAtTimeOfQuote: 4100,
        variationStatus: 'Original'
      },
      {
        id: 'boq-item-502',
        no: '2.0',
        name: 'Automatic Frameless Bi-Parting Sliding System',
        description: 'Heavy duty commercial automated sliding door with microwave radar sensors',
        itemType: 'Main',
        category: 'Aluminium',
        unit: 'Sets',
        qty: 2,
        rate: 1090000,
        discountPercent: 0,
        amount: 2180000,
        variantCode: 'AL-AUTO-01',
        costAtTimeOfQuote: 780000,
        variationStatus: 'Original'
      }
    ],
    terms: DEFAULT_TERMS,
    paymentTiers: [
      { id: 'pt-51', phase: 'Advance Payment', percentage: 40, amount: 2960000, status: 'Paid' },
      { id: 'pt-52', phase: 'Progress Claim', percentage: 40, amount: 2960000, status: 'Paid' },
      { id: 'pt-53', phase: 'Handover & Retention', percentage: 20, amount: 1480000, status: 'Paid' }
    ]
  },
  {
    id: 'proj-kandy-06',
    projectName: 'Kandy Heritage Arcade - Skylight Canopy Renovation',
    originalQuoteNo: 'QT-2025-1102',
    startDate: '2025-10-05',
    status: 'Completed',
    totalValue: 1850000,
    currency: 'Rs.',
    client: SAMPLE_CLIENTS[1],
    items: [
      {
        id: 'boq-item-601',
        no: '1.0',
        name: 'Structural Laminated Skylight Canopy',
        description: 'Steel-reinforced architectural canopy with 17.52mm tinted heat-strengthened laminated glass',
        itemType: 'Main',
        category: 'Glass',
        unit: 'sqft',
        qty: 250,
        rate: 7400,
        discountPercent: 0,
        amount: 1850000,
        variantCode: 'GL-SKY-01',
        costAtTimeOfQuote: 5900,
        variationStatus: 'Original'
      }
    ],
    terms: DEFAULT_TERMS,
    paymentTiers: [
      { id: 'pt-61', phase: 'Full Contract Settlement', percentage: 100, amount: 1850000, status: 'Paid' }
    ]
  },
  {
    id: 'proj-orion-07',
    projectName: 'Orion City IT Campus - Entrance Portico & Louver Screen',
    originalQuoteNo: 'QT-2025-1215',
    startDate: '2025-11-20',
    status: 'Completed',
    totalValue: 4350000,
    currency: 'Rs.',
    client: SAMPLE_CLIENTS[0],
    items: [
      {
        id: 'boq-item-701',
        no: '1.0',
        name: 'Architectural Exterior Sunshade Louvers',
        description: 'Anodized 25-micron solar shading elliptical louvers with mechanical angle adjustment',
        itemType: 'Main',
        category: 'Aluminium',
        unit: 'sqft',
        qty: 650,
        rate: 4200,
        discountPercent: 0,
        amount: 2730000,
        variantCode: 'AL-LV-004',
        costAtTimeOfQuote: 2850,
        variationStatus: 'Original'
      },
      {
        id: 'boq-item-702',
        no: '2.0',
        name: 'Acoustic Sound Isolation Enclosures',
        description: 'Double glazed acoustic meeting cubicles with perimeter acoustic drops',
        itemType: 'Main',
        category: 'Glass',
        unit: 'sqft',
        qty: 360,
        rate: 4500,
        discountPercent: 0,
        amount: 1620000,
        variantCode: 'GL-AC-002',
        costAtTimeOfQuote: 3100,
        variationStatus: 'Original'
      }
    ],
    terms: DEFAULT_TERMS,
    paymentTiers: [
      { id: 'pt-71', phase: 'Advance Payment', percentage: 50, amount: 2175000, status: 'Paid' },
      { id: 'pt-72', phase: 'Final Handover', percentage: 50, amount: 2175000, status: 'Paid' }
    ]
  },
  {
    id: 'proj-airport-08',
    projectCode: 'PRJ-2025-008',
    projectName: 'BIA Terminal 2 Concourse - Security Glazing Package',
    originalQuoteNo: 'QT-2025-0604',
    startDate: '2025-06-01',
    status: 'Completed',
    category: 'Glass',
    siteAddress: 'Katunayake International Airport, Katunayake',
    totalValue: 8600000,
    currency: 'Rs.',
    client: SAMPLE_CLIENTS[1],
    items: [
      {
        id: 'boq-item-801',
        no: '1.0',
        name: 'Curtain Wall System (Heavy-Duty Windload)',
        description: 'Thermally broken curtain wall system tested to 2.4 kPa dynamic wind pressures',
        itemType: 'Main',
        category: 'Aluminium',
        unit: 'sqft',
        qty: 1200,
        rate: 4800,
        discountPercent: 0,
        amount: 5760000,
        variantCode: 'AL-CW-001',
        costAtTimeOfQuote: 3350,
        variationStatus: 'Original'
      },
      {
        id: 'boq-item-802',
        no: '2.0',
        name: 'High-Impact Acoustic Laminated Glazing',
        description: '21.52mm SentryGlas acoustic laminated safety panels for high-traffic public terminal',
        itemType: 'Main',
        category: 'Glass',
        unit: 'sqft',
        qty: 400,
        rate: 7100,
        discountPercent: 0,
        amount: 2840000,
        variantCode: 'GL-SEC-01',
        costAtTimeOfQuote: 4900,
        variationStatus: 'Original'
      }
    ],
    terms: DEFAULT_TERMS,
    paymentTiers: [
      { id: 'pt-81', phase: 'Advance Payment', percentage: 40, amount: 3440000, status: 'Paid' },
      { id: 'pt-82', phase: 'Installation Progress', percentage: 40, amount: 3440000, status: 'Paid' },
      { id: 'pt-83', phase: 'Handover & Certification', percentage: 20, amount: 1720000, status: 'Paid' }
    ]
  },
  {
    id: 'proj-crescat-09',
    projectCode: 'PRJ-2026-009',
    projectName: 'Crescat Boulevard Penthouse - Frameless Glazing',
    originalQuoteNo: 'QT-2026-1105',
    startDate: '2026-09-20',
    status: 'New Request',
    category: 'Glass',
    siteAddress: '89 Galle Road, Colombo 03',
    totalValue: 1850000,
    currency: 'Rs.',
    client: SAMPLE_CLIENTS[0],
    items: [
      {
        id: 'boq-item-901',
        no: '1.0',
        name: 'Frameless Glass Balustrade & Windscreen',
        description: '15mm toughened laminated ultra-clear glass with recessed floor profile',
        itemType: 'Main',
        category: 'Glass',
        unit: 'L.ft',
        qty: 85,
        rate: 14500,
        discountPercent: 0,
        amount: 1232500,
        variantCode: 'GL-BL-001',
        costAtTimeOfQuote: 9800,
        variationStatus: 'Original'
      },
      {
        id: 'boq-item-902',
        no: '2.0',
        name: 'Concealed Motorized Roller Shading',
        description: 'Perimeter acoustic ceiling pocket with sun-filtering architectural fabric',
        itemType: 'Main',
        category: 'Aluminium',
        unit: 'Sets',
        qty: 3,
        rate: 205833,
        discountPercent: 0,
        amount: 617500,
        variantCode: 'AL-SH-001',
        costAtTimeOfQuote: 142000,
        variationStatus: 'Original'
      }
    ],
    terms: DEFAULT_TERMS,
    paymentTiers: [
      { id: 'pt-91', phase: 'Advance Payment', percentage: 50, amount: 925000, status: 'Pending' },
      { id: 'pt-92', phase: 'Final Handover', percentage: 50, amount: 925000, status: 'Pending' }
    ]
  }
];

export const SAMPLE_QUOTES: Quote[] = [
  {
    id: 'quote-altair-01',
    quoteNo: 'QT-2026-1042',
    projectId: 'proj-altair-01',
    projectCode: 'PRJ-2026-001',
    projectName: 'Altair Tower - Luxury Façade & Glazing Package',
    workSiteLocation: '45, Sir James Pieris Mawatha, Colombo 02',
    salesRepresentative: 'Alexander Vance',
    quoteType: 'Detailed BOQ',
    pricingMethod: 'Unit Rate',
    projectStage: 'Detailed BOQ',
    scopeCoverage: 'Supply & Install',
    version: 1,
    submittedDate: '2026-01-15',
    validityDays: 30,
    validUntil: '2026-02-14',
    currency: 'Rs.',
    status: QuoteStatus.PROJECT,
    client: SAMPLE_CLIENTS[0],
    discountPercent: 0,
    taxPercent: 0,
    isTaxInclusive: true,
    advancePercent: 30,
    estimatedDeliveryDays: 45,
    items: [
      {
        id: 'boq-item-101',
        no: '1.0',
        name: 'Curtain Wall System (Double Glazed Low-E)',
        description: 'Thermally broken aluminium mullions & transoms with 24mm DGU Low-E glass panels',
        itemType: 'Main',
        category: 'Aluminium',
        unit: 'sqft',
        qty: 450,
        rate: 4200,
        discountPercent: 0,
        amount: 1890000,
        productCode: 'GL-CW-001',
        variantCode: 'AL-CW-001',
        variantBarcode: 'VAR-ALCW-001',
        barcode: 'VAR-ALCW-001',
        costAtTimeOfQuote: 2950,
        variationStatus: 'Original'
      },
      {
        id: 'boq-item-102',
        no: '2.0',
        name: 'Heavy Duty Sliding Balcony Doors',
        description: 'Euro-groove 3-track sliding door system with multi-point flush shootbolts',
        itemType: 'Main',
        category: 'Aluminium',
        unit: 'sqft',
        qty: 240,
        rate: 3800,
        discountPercent: 0,
        amount: 912000,
        productCode: 'AL-DR-003',
        variantCode: 'AL-DR-003',
        variantBarcode: 'VAR-ALDR-003',
        barcode: 'VAR-ALDR-003',
        costAtTimeOfQuote: 2650,
        variationStatus: 'Original'
      },
      {
        id: 'boq-item-103',
        no: '3.0',
        name: 'Frameless Glass Balustrade (15mm Tempered)',
        description: 'Bottom aluminium shoe channel with continuous LED recess and 15mm clear tempered glass',
        itemType: 'Main',
        category: 'Glass',
        unit: 'ft',
        qty: 120,
        rate: 5400,
        discountPercent: 0,
        amount: 648000,
        productCode: 'GL-BL-001',
        variantCode: 'GL-BL-001',
        variantBarcode: 'VAR-GLBL-001',
        barcode: 'VAR-GLBL-001',
        costAtTimeOfQuote: 3800,
        variationStatus: 'Original'
      }
    ],
    terms: DEFAULT_TERMS,
    additionalCharges: [],
    paymentTiers: [
      { id: 'pt-1', phase: 'Advance Payment', percentage: 30, amount: 1035000, status: 'Paid' },
      { id: 'pt-2', phase: 'Materials Procurement', percentage: 40, amount: 1380000, status: 'Paid' },
      { id: 'pt-3', phase: 'Testing & Handover', percentage: 30, amount: 1035000, status: 'Pending' }
    ]
  },
  {
    id: 'quote-portcity-02',
    quoteNo: 'QT-2026-1088',
    projectId: 'proj-portcity-02',
    projectCode: 'PRJ-2026-002',
    projectName: 'Port City Marine Terminal - Acoustic Partitions & Louvers',
    workSiteLocation: 'Financial District, Colombo Port City',
    salesRepresentative: 'Mira Brown',
    quoteType: 'Detailed BOQ',
    pricingMethod: 'Unit Rate',
    projectStage: 'Detailed BOQ',
    scopeCoverage: 'Supply & Install',
    version: 1,
    submittedDate: '2026-02-01',
    validityDays: 30,
    validUntil: '2026-03-03',
    currency: 'Rs.',
    status: QuoteStatus.PROJECT,
    client: SAMPLE_CLIENTS[1],
    discountPercent: 0,
    taxPercent: 0,
    isTaxInclusive: true,
    advancePercent: 40,
    estimatedDeliveryDays: 60,
    items: [
      {
        id: 'boq-item-201',
        no: '1.0',
        name: 'Acoustic Soundproof Glass Partitions',
        description: 'Double glazed 12mm + acoustic PVB + 10mm partition with perimeter neoprene seals',
        itemType: 'Main',
        category: 'Glass',
        unit: 'sqft',
        qty: 320,
        rate: 4500,
        discountPercent: 0,
        amount: 1440000,
        productCode: 'GL-AC-002',
        variantCode: 'GL-AC-002',
        variantBarcode: 'VAR-GLAC-002',
        barcode: 'VAR-GLAC-002',
        costAtTimeOfQuote: 3100,
        variationStatus: 'Original'
      },
      {
        id: 'boq-item-202',
        no: '2.0',
        name: 'Aerodynamic Architectural Louver Screen',
        description: 'Z-profile architectural extruded aluminium storm louvers with bird mesh',
        itemType: 'Main',
        category: 'Aluminium',
        unit: 'sqft',
        qty: 200,
        rate: 3700,
        discountPercent: 0,
        amount: 740000,
        productCode: 'AL-LV-004',
        variantCode: 'AL-LV-004',
        variantBarcode: 'VAR-ALLV-004',
        barcode: 'VAR-ALLV-004',
        costAtTimeOfQuote: 2550,
        variationStatus: 'Original'
      }
    ],
    terms: DEFAULT_TERMS,
    additionalCharges: [],
    paymentTiers: [
      { id: 'pt-21', phase: 'Mobilization', percentage: 40, amount: 872000, status: 'Paid' },
      { id: 'pt-22', phase: 'Site Erection', percentage: 60, amount: 1308000, status: 'Pending' }
    ]
  },
  {
    id: 'quote-crescat-03',
    quoteNo: 'QT-2026-1105',
    projectId: 'proj-crescat-09',
    projectCode: 'PRJ-2026-009',
    projectName: 'Crescat Boulevard Penthouse - Frameless Glazing',
    workSiteLocation: '89 Galle Road, Colombo 03',
    salesRepresentative: 'David Lee',
    quoteType: 'Detailed BOQ',
    pricingMethod: 'Unit Rate',
    projectStage: 'Detailed BOQ',
    scopeCoverage: 'Supply & Install',
    version: 1,
    submittedDate: '2026-09-20',
    validityDays: 14,
    validUntil: '2026-10-04',
    currency: 'Rs.',
    status: QuoteStatus.SENT,
    client: SAMPLE_CLIENTS[0],
    discountPercent: 0,
    taxPercent: 0,
    isTaxInclusive: true,
    advancePercent: 50,
    estimatedDeliveryDays: 21,
    items: [
      {
        id: 'boq-item-901',
        no: '1.0',
        name: 'Frameless Glass Balustrade & Windscreen',
        description: '15mm toughened laminated ultra-clear glass with recessed floor profile',
        itemType: 'Main',
        category: 'Glass',
        unit: 'ft',
        qty: 85,
        rate: 14500,
        discountPercent: 0,
        amount: 1232500,
        productCode: 'GL-BL-001',
        variantCode: 'GL-BL-001',
        variantBarcode: 'VAR-GLBL-001',
        barcode: 'VAR-GLBL-001',
        costAtTimeOfQuote: 9800,
        variationStatus: 'Original'
      },
      {
        id: 'boq-item-902',
        no: '2.0',
        name: 'Concealed Motorized Roller Shading',
        description: 'Perimeter acoustic ceiling pocket with sun-filtering architectural fabric',
        itemType: 'Main',
        category: 'Aluminium',
        unit: 'Set',
        qty: 3,
        rate: 205833,
        discountPercent: 0,
        amount: 617500,
        productCode: 'AL-SH-001',
        variantCode: 'AL-SH-001',
        variantBarcode: 'VAR-ALSH-001',
        barcode: 'VAR-ALSH-001',
        costAtTimeOfQuote: 142000,
        variationStatus: 'Original'
      }
    ],
    terms: DEFAULT_TERMS,
    additionalCharges: [],
    paymentTiers: [
      { id: 'pt-91', phase: 'Advance Payment', percentage: 50, amount: 925000, status: 'Pending' },
      { id: 'pt-92', phase: 'Final Handover', percentage: 50, amount: 925000, status: 'Pending' }
    ]
  }
];

export const SAMPLE_INVOICES: Invoice[] = [
  {
    id: 'inv-altair-01',
    invoiceNo: 'INV-2026-0101',
    type: InvoiceType.ADVANCE,
    status: InvoiceStatus.PAID,
    date: '2026-01-20',
    dueDate: '2026-02-05',
    projectId: 'proj-altair-01',
    projectCode: 'PRJ-2026-001',
    projectName: 'Altair Tower - Luxury Façade & Glazing Package',
    quoteId: 'quote-altair-01',
    client: SAMPLE_CLIENTS[0],
    customerId: SAMPLE_CLIENTS[0].id,
    subTotal: 1035000,
    discountTotal: 0,
    taxTotal: 0,
    grandTotal: 1035000,
    amountPaid: 1035000,
    balanceDue: 0,
    createdAt: '2026-01-20T00:00:00.000Z',
    updatedAt: '2026-01-20T00:00:00.000Z',
    currency: 'Rs.',
    items: [
      {
        id: 'inv-item-1',
        description: 'Advance Mobilization Payment (30%) - Altair Façade Package',
        qty: 1,
        unit: 'Nos',
        rate: 1035000,
        amount: 1035000,
        taxPercent: 0,
        discountPercent: 0
      }
    ]
  },
  {
    id: 'inv-altair-02',
    invoiceNo: 'INV-2026-0102',
    type: InvoiceType.PROGRESS_BILLING,
    status: InvoiceStatus.SENT,
    date: '2026-02-28',
    dueDate: '2026-03-15',
    projectId: 'proj-altair-01',
    projectCode: 'PRJ-2026-001',
    projectName: 'Altair Tower - Luxury Façade & Glazing Package',
    quoteId: 'quote-altair-01',
    client: SAMPLE_CLIENTS[0],
    customerId: SAMPLE_CLIENTS[0].id,
    subTotal: 1380000,
    discountTotal: 0,
    taxTotal: 0,
    grandTotal: 1380000,
    amountPaid: 0,
    balanceDue: 1380000,
    createdAt: '2026-02-28T00:00:00.000Z',
    updatedAt: '2026-02-28T00:00:00.000Z',
    currency: 'Rs.',
    items: [
      {
        id: 'inv-item-2',
        description: 'Progress Claim 01: Materials Procurement & Mullion Extrusion Assembly',
        qty: 1,
        unit: 'Nos',
        rate: 1380000,
        amount: 1380000,
        taxPercent: 0,
        discountPercent: 0
      }
    ]
  },
  {
    id: 'inv-portcity-01',
    invoiceNo: 'INV-2026-0201',
    type: InvoiceType.ADVANCE,
    status: InvoiceStatus.PAID,
    date: '2026-02-10',
    dueDate: '2026-02-25',
    projectId: 'proj-portcity-02',
    projectCode: 'PRJ-2026-002',
    projectName: 'Port City Marine Terminal - Acoustic Partitions & Louvers',
    quoteId: 'quote-portcity-02',
    client: SAMPLE_CLIENTS[1],
    customerId: SAMPLE_CLIENTS[1].id,
    subTotal: 872000,
    discountTotal: 0,
    taxTotal: 0,
    grandTotal: 872000,
    amountPaid: 872000,
    balanceDue: 0,
    createdAt: '2026-02-10T00:00:00.000Z',
    updatedAt: '2026-02-10T00:00:00.000Z',
    currency: 'Rs.',
    items: [
      {
        id: 'inv-item-3',
        description: 'Advance Mobilization Payment (40%) - Marine Terminal Partitions',
        qty: 1,
        unit: 'Nos',
        rate: 872000,
        amount: 872000,
        taxPercent: 0,
        discountPercent: 0
      }
    ]
  }
];


